import type { GridSlot, Role, UnitRank, UnitTemplate } from '../shared/types.js';
import { MAINLINE_BIOME_ENCOUNTERS } from './mainlineBiomeEncounters.js';
import { MAINLINE_CAP_BLEND_ENCOUNTERS } from './mainlineCapBlendEncounters.js';

export interface EnemySpec {
  name: string;
  role: Role;
  job: UnitTemplate['job'];
  slot: GridSlot;
  damageSchool?: 'phys' | 'spirit';
  atk: number;
  def: number;
  res: number;
  maxHp: number;
  spd: number;
  critRating?: number;
  critDmgRating?: number;
  penRating?: number;
  masteryRating?: number;
  tenacityRating?: number;
  fortuneRating?: number;
  skillId: string;
  /** 开战盾（叠盾题用，不走装词缀） */
  startShield?: number;
  /** 驱散只削该比例的盾，缺省整层 */
  shieldPurgeFactor?: number;
  /** 抗控分级，默认 normal */
  rank?: UnitRank;
}

/** 单场战斗回合上限（整轮数）；未写则用 DEFAULT_BATTLE_MAX_TURNS */
export const DEFAULT_BATTLE_MAX_TURNS = 25;

export interface EncounterDef {
  id: string;
  name: string;
  /** 战前一句：堆装/站位方向（不锁进门） */
  prepHint?: string;
  /** 本场回合上限；速战类可更短 */
  maxTurns?: number;
  enemies: EnemySpec[];
}

/**
 * 遭遇表（2026-08-04 解法卡关 · 防御×0.5 后）：
 *
 * | 遭遇 | 卡住 | 破解 |
 * | wall | 无破甲磨不动 | 破甲（悟空/诸葛） |
 * | archers | 磨前门时被后排点杀 | 穿透先斩弓 |
 * | raiders | 控+双影刃秒玻璃 | 盾/坦/奶 |
 * | spirit_wall | 高物防（力队吃瘪） | 深破甲；镜渊 pressure>1 |
 * | chaos_rite | 群扰乱 | 斩祭师/续航/控场 |
 * | boss_warden | 免疫硬控+厚血 | 破甲/流血，先清侧卫 |
 * | oil_cask | 后排奶抬不完 | 禁疗 / 斩杀 / 穿透点奶 |
 * | shield_stack | 盾挡完输出 | 对盾增伤 |
 *
 * 基线按开局/猎装 pressure=1；章档×本种（二章 1.25、三章 1.55、镜渊再 ×1.3）。
 * 猎装旧题（弓/速）在三章压力下才卡穿透/坦奶；油桶/叠盾二章解锁后在 p1 即可卡关。
 */
/** 猎装/战前 UI：首领遭遇 id 均以 boss_ 开头 */
export function isBossEncounterId(encounterId: string): boolean {
  return encounterId.startsWith('boss_');
}

/** 八题配方遭遇（主线第三波「精锐」） */
const MAINLINE_RECIPE_ENCOUNTER_IDS = new Set([
  'wall',
  'archers',
  'raiders',
  'spirit_wall',
  'chaos_rite',
  'oil_cask',
  'shield_stack',
]);

export type EncounterDisplayTier = 'normal' | 'elite' | 'boss';

/** 战前/顶栏阶位（与格子 rank 标识一致；小怪波为 normal） */
export function encounterDisplayTier(encounterId: string): EncounterDisplayTier {
  if (isBossEncounterId(encounterId)) return 'boss';
  if (MAINLINE_RECIPE_ENCOUNTER_IDS.has(encounterId)) return 'elite';
  if (encounterId.startsWith('mainline_blend_')) return 'elite';
  return 'normal';
}

/**
 * 敌方九宫 slot：1–3 前排、4–6 中排、7–9 后排（UI 上后排远离交锋线）。
 * boss_*：金框首领（rank:boss）尽量在中排 5 或后排 7–9，前排多为杂兵/精英挡刀；人数 3–4 为主。
 */
const BASE_ENCOUNTERS: EncounterDef[] = [
  {
    id: 'gate_skirmish',
    name: '关前前锋',
    prepHint: '两名关丁练手：熟悉破阵与换位，下一波才是盾墙',
    maxTurns: 18,
    enemies: [
      {
        name: '关丁甲',
        role: 'tank',
        job: 'vanguard',
        slot: 1,
        atk: 11,
        def: 14,
        res: 8,
        maxHp: 95,
        spd: 8,
        fortuneRating: 8,
        skillId: 'mob_smash',
      },
      {
        name: '关丁乙',
        role: 'tank',
        job: 'vanguard',
        slot: 3,
        atk: 10,
        def: 13,
        res: 8,
        maxHp: 90,
        spd: 8,
        fortuneRating: 8,
        skillId: 'mob_smash',
      },
      {
        name: '关丁弓',
        role: 'st_burst',
        job: 'ranger',
        slot: 9,
        atk: 12,
        def: 5,
        res: 4,
        maxHp: 58,
        spd: 14,
        skillId: 'mob_arrow',
      },
    ],
  },
  {
    id: 'wall',
    name: '盾墙巡逻',
    prepHint: '前排极肉：破甲/群攻磨盾，术士可禁疗 · 猎装刷装',
    enemies: [
      {
        name: '铁壁恶徒',
        role: 'tank',
        job: 'vanguard',
        slot: 1,
        atk: 16,
        def: 36,
        res: 18,
        maxHp: 225,
        spd: 7,
        tenacityRating: 22,
        fortuneRating: 14,
        skillId: 'mob_guard',
        rank: 'elite',
      },
      {
        name: '厚甲恶徒',
        role: 'tank',
        job: 'vanguard',
        slot: 3,
        atk: 15,
        def: 36,
        res: 17,
        maxHp: 220,
        spd: 7,
        tenacityRating: 18,
        fortuneRating: 12,
        skillId: 'mob_smash',
      },
    ],
  },
  {
    id: 'archers',
    name: '后排伏击',
    prepHint: '先撕前排否则后排点杀：穿透/切后 · 猎装量、镜渊对症 T3',
    maxTurns: 20,
    enemies: [
      {
        name: '挡箭杂兵',
        role: 'tank',
        job: 'vanguard',
        slot: 2,
        atk: 12,
        def: 16,
        res: 10,
        maxHp: 250,
        spd: 8,
        fortuneRating: 8,
        skillId: 'mob_smash',
      },
      {
        name: '伏击弓手甲',
        role: 'st_burst',
        job: 'ranger',
        slot: 7,
        atk: 21,
        def: 5,
        res: 4,
        maxHp: 66,
        spd: 16,
        critRating: 34,
        critDmgRating: 24,
        fortuneRating: 6,
        skillId: 'mob_arrow',
      },
      {
        name: '伏击弓手乙',
        role: 'st_burst',
        job: 'ranger',
        slot: 9,
        atk: 20,
        def: 5,
        res: 4,
        maxHp: 62,
        spd: 16,
        critRating: 34,
        critDmgRating: 24,
        fortuneRating: 6,
        skillId: 'mob_arrow',
      },
    ],
  },
  {
    id: 'raiders',
    name: '速攻刺客',
    prepHint: '身法快带控：护盾/坦阵，优先秒脆皮后排',
    enemies: [
      {
        name: '点穴客',
        role: 'st_ctrl',
        job: 'warlock',
        slot: 5,
        atk: 16,
        def: 9,
        res: 8,
        maxHp: 105,
        spd: 16,
        masteryRating: 26,
        fortuneRating: 11,
        skillId: 'mob_stun',
      },
      {
        name: '迟滞客',
        role: 'st_ctrl',
        job: 'warlock',
        slot: 4,
        atk: 15,
        def: 9,
        res: 8,
        maxHp: 100,
        spd: 15,
        masteryRating: 22,
        fortuneRating: 10,
        skillId: 'mob_slow',
      },
      {
        name: '催眠客',
        role: 'st_ctrl',
        job: 'warlock',
        slot: 8,
        atk: 15,
        def: 8,
        res: 7,
        maxHp: 96,
        spd: 14,
        masteryRating: 24,
        fortuneRating: 10,
        skillId: 'mob_sleep',
      },
      {
        name: '影刃',
        role: 'st_burst',
        job: 'assassin',
        slot: 9,
        atk: 22,
        def: 5,
        res: 4,
        maxHp: 88,
        spd: 16,
        critRating: 30,
        critDmgRating: 22,
        fortuneRating: 10,
        skillId: 'mob_arrow',
      },
    ],
  },
  {
    id: 'spirit_wall',
    name: '铁壁灵阵',
    prepHint: '物防极高：灵伤或裂甲/破甲 T3 · 解法装→镜渊试炼',
    enemies: [
      {
        name: '铁壁灵卫',
        role: 'tank',
        job: 'vanguard',
        slot: 1,
        atk: 18,
        def: 60,
        res: 14,
        maxHp: 240,
        spd: 7,
        tenacityRating: 26,
        fortuneRating: 16,
        skillId: 'mob_guard',
        rank: 'elite',
      },
      {
        name: '铁壁灵卫乙',
        role: 'tank',
        job: 'vanguard',
        slot: 3,
        atk: 17,
        def: 56,
        res: 13,
        maxHp: 220,
        spd: 7,
        fortuneRating: 14,
        skillId: 'mob_smash',
      },
      {
        name: '灵矢手',
        role: 'st_burst',
        job: 'mage',
        slot: 8,
        atk: 20,
        def: 7,
        res: 12,
        maxHp: 120,
        spd: 16,
        critRating: 34,
        fortuneRating: 10,
        skillId: 'mob_spirit_bolt',
      },
    ],
  },
  {
    id: 'chaos_rite',
    name: '乱心仪式',
    prepHint: '群乱心：先斩祭师，净化/护盾稳住',
    enemies: [
      {
        name: '乱心祭师',
        role: 'aoe_ctrl',
        job: 'warlock',
        slot: 5,
        atk: 24,
        def: 12,
        res: 16,
        maxHp: 200,
        spd: 14,
        masteryRating: 42,
        fortuneRating: 15,
        skillId: 'mob_chaos_wave',
        rank: 'elite',
      },
      {
        name: '附和者',
        role: 'st_ctrl',
        job: 'warlock',
        slot: 4,
        atk: 18,
        def: 9,
        res: 10,
        maxHp: 115,
        spd: 15,
        masteryRating: 26,
        fortuneRating: 12,
        skillId: 'mob_berserk',
      },
      {
        name: '附和者乙',
        role: 'st_ctrl',
        job: 'warlock',
        slot: 6,
        atk: 18,
        def: 9,
        res: 10,
        maxHp: 115,
        spd: 15,
        masteryRating: 26,
        fortuneRating: 12,
        skillId: 'mob_sleep',
      },
      {
        name: '乱心刀客',
        role: 'st_burst',
        job: 'assassin',
        slot: 9,
        atk: 17,
        def: 6,
        res: 5,
        maxHp: 90,
        spd: 14,
        critRating: 20,
        fortuneRating: 10,
        skillId: 'mob_arrow',
      },
    ],
  },
  {
    id: 'boss_warden',
    name: '守卫首领',
    prepHint: '中排镇狱、后排侧卫：破甲/流血，先清后排再集火首领',
    enemies: [
      {
        name: '镇狱守卫',
        role: 'tank',
        job: 'vanguard',
        slot: 5,
        atk: 23,
        def: 50,
        res: 24,
        maxHp: 560,
        spd: 10,
        tenacityRating: 28,
        masteryRating: 26,
        fortuneRating: 18,
        skillId: 'mob_boss_slam',
        rank: 'boss',
      },
      {
        name: '侧卫甲',
        role: 'st_burst',
        job: 'assassin',
        slot: 7,
        atk: 22,
        def: 7,
        res: 5,
        maxHp: 115,
        spd: 15,
        critRating: 34,
        fortuneRating: 11,
        skillId: 'mob_arrow',
      },
      {
        name: '侧卫乙',
        role: 'st_heal',
        job: 'healer',
        slot: 9,
        atk: 20,
        def: 10,
        res: 14,
        maxHp: 130,
        spd: 12,
        masteryRating: 28,
        fortuneRating: 12,
        skillId: 'mob_heal_block',
      },
    ],
  },
  {
    id: 'oil_cask',
    name: '油桶续命',
    prepHint: '后排双医抬血：禁疗/斩杀/穿透点医 · 净疗/禁疗 T3→镜渊',
    enemies: [
      {
        name: '油桶门板',
        role: 'tank',
        job: 'vanguard',
        slot: 2,
        atk: 12,
        def: 22,
        res: 14,
        maxHp: 480,
        spd: 7,
        fortuneRating: 10,
        skillId: 'mob_smash',
      },
      {
        name: '油桶刀手',
        role: 'st_burst',
        job: 'assassin',
        slot: 5,
        atk: 13,
        def: 8,
        res: 7,
        maxHp: 85,
        spd: 12,
        critRating: 16,
        fortuneRating: 8,
        skillId: 'mob_arrow',
      },
      {
        name: '油桶医士',
        role: 'st_heal',
        job: 'healer',
        slot: 7,
        atk: 36,
        def: 6,
        res: 12,
        maxHp: 72,
        spd: 16,
        masteryRating: 42,
        fortuneRating: 12,
        skillId: 'mob_mend',
      },
      {
        name: '油桶药童',
        role: 'st_heal',
        job: 'healer',
        slot: 9,
        atk: 32,
        def: 5,
        res: 11,
        maxHp: 68,
        spd: 15,
        masteryRating: 36,
        fortuneRating: 10,
        skillId: 'mob_mend',
      },
    ],
  },
  {
    id: 'shield_stack',
    name: '叠盾铁阵',
    prepHint: '反复叠盾：对盾增伤/破盾 T3 · 解法装→镜渊试炼',
    enemies: [
      {
        name: '叠盾甲',
        role: 'tank',
        job: 'vanguard',
        slot: 2,
        atk: 30,
        def: 16,
        res: 12,
        maxHp: 210,
        spd: 10,
        fortuneRating: 10,
        skillId: 'mob_stack_shield',
        startShield: 180,
        shieldPurgeFactor: 0.22,
      },
      {
        name: '叠盾乙',
        role: 'tank',
        job: 'vanguard',
        slot: 6,
        atk: 30,
        def: 16,
        res: 12,
        maxHp: 210,
        spd: 10,
        fortuneRating: 10,
        skillId: 'mob_stack_shield',
        startShield: 180,
        shieldPurgeFactor: 0.22,
      },
      {
        name: '叠盾丙',
        role: 'group_amp',
        job: 'support',
        slot: 8,
        atk: 32,
        def: 14,
        res: 13,
        maxHp: 190,
        spd: 13,
        fortuneRating: 10,
        skillId: 'mob_stack_shield',
        startShield: 200,
        shieldPurgeFactor: 0.22,
      },
    ],
  },
  {
    id: 'boss_wall',
    name: '盾墙首领',
    prepHint: '前排双盾挡刀、中排统领：破甲/群攻磨穿再收',
    enemies: [
      {
        name: '盾卫左翼',
        role: 'tank',
        job: 'vanguard',
        slot: 1,
        atk: 15,
        def: 36,
        res: 18,
        maxHp: 250,
        spd: 7,
        tenacityRating: 18,
        fortuneRating: 12,
        skillId: 'mob_smash',
        rank: 'elite',
      },
      {
        name: '盾卫右翼',
        role: 'tank',
        job: 'vanguard',
        slot: 3,
        atk: 15,
        def: 36,
        res: 18,
        maxHp: 250,
        spd: 7,
        tenacityRating: 18,
        fortuneRating: 12,
        skillId: 'mob_smash',
        rank: 'elite',
      },
      {
        name: '铁壁统领',
        role: 'tank',
        job: 'vanguard',
        slot: 5,
        atk: 19,
        def: 42,
        res: 20,
        maxHp: 480,
        spd: 8,
        tenacityRating: 26,
        fortuneRating: 16,
        skillId: 'mob_guard',
        rank: 'boss',
      },
    ],
  },
  {
    id: 'boss_archers',
    name: '伏弓首领',
    prepHint: '前排挡箭、后排金弓首领：穿透/切后',
    maxTurns: 22,
    enemies: [
      {
        name: '挡箭杂兵',
        role: 'tank',
        job: 'vanguard',
        slot: 1,
        atk: 11,
        def: 16,
        res: 10,
        maxHp: 150,
        spd: 8,
        fortuneRating: 8,
        skillId: 'mob_smash',
      },
      {
        name: '挡箭统领',
        role: 'tank',
        job: 'vanguard',
        slot: 2,
        atk: 15,
        def: 24,
        res: 12,
        maxHp: 340,
        spd: 9,
        fortuneRating: 12,
        skillId: 'mob_guard',
        rank: 'elite',
      },
      {
        name: '伏弓首领',
        role: 'st_burst',
        job: 'ranger',
        slot: 8,
        atk: 26,
        def: 6,
        res: 5,
        maxHp: 150,
        spd: 17,
        critRating: 38,
        critDmgRating: 28,
        fortuneRating: 10,
        skillId: 'mob_arrow',
        rank: 'boss',
      },
      {
        name: '伏弓副手',
        role: 'st_burst',
        job: 'ranger',
        slot: 9,
        atk: 24,
        def: 5,
        res: 4,
        maxHp: 120,
        spd: 16,
        critRating: 34,
        fortuneRating: 8,
        skillId: 'mob_arrow',
      },
    ],
  },
  {
    id: 'boss_raiders',
    name: '速攻首领',
    prepHint: '两翼突进、中排控场首领：先断控再收后排',
    enemies: [
      {
        name: '突进客',
        role: 'st_burst',
        job: 'assassin',
        slot: 1,
        atk: 18,
        def: 6,
        res: 5,
        maxHp: 100,
        spd: 16,
        critRating: 28,
        fortuneRating: 10,
        skillId: 'mob_arrow',
      },
      {
        name: '乱阵首领',
        role: 'st_ctrl',
        job: 'warlock',
        slot: 5,
        atk: 20,
        def: 11,
        res: 10,
        maxHp: 310,
        spd: 17,
        masteryRating: 32,
        fortuneRating: 14,
        skillId: 'mob_stun',
        rank: 'boss',
      },
      {
        name: '突进客',
        role: 'st_burst',
        job: 'assassin',
        slot: 3,
        atk: 18,
        def: 6,
        res: 5,
        maxHp: 100,
        spd: 16,
        critRating: 28,
        fortuneRating: 10,
        skillId: 'mob_arrow',
      },
      {
        name: '影刃魁首',
        role: 'st_burst',
        job: 'assassin',
        slot: 9,
        atk: 26,
        def: 6,
        res: 5,
        maxHp: 130,
        spd: 17,
        critRating: 34,
        fortuneRating: 12,
        skillId: 'mob_arrow',
        rank: 'elite',
      },
    ],
  },
  {
    id: 'boss_oil',
    name: '油火首领',
    prepHint: '前排门板、后排医魁首领：禁疗/穿透点后排',
    enemies: [
      {
        name: '油火统领',
        role: 'tank',
        job: 'vanguard',
        slot: 2,
        atk: 16,
        def: 26,
        res: 16,
        maxHp: 500,
        spd: 8,
        fortuneRating: 12,
        skillId: 'mob_smash',
        rank: 'elite',
      },
      {
        name: '油桶刀手',
        role: 'st_burst',
        job: 'assassin',
        slot: 5,
        atk: 13,
        def: 8,
        res: 7,
        maxHp: 90,
        spd: 12,
        fortuneRating: 8,
        skillId: 'mob_arrow',
      },
      {
        name: '油火医魁',
        role: 'st_heal',
        job: 'healer',
        slot: 8,
        atk: 40,
        def: 7,
        res: 14,
        maxHp: 120,
        spd: 16,
        masteryRating: 46,
        fortuneRating: 14,
        skillId: 'mob_mend',
        rank: 'boss',
      },
      {
        name: '油桶药童',
        role: 'st_heal',
        job: 'healer',
        slot: 9,
        atk: 32,
        def: 5,
        res: 11,
        maxHp: 72,
        spd: 15,
        masteryRating: 36,
        fortuneRating: 10,
        skillId: 'mob_mend',
      },
    ],
  },
  {
    id: 'boss_spirit_wall',
    name: '灵阵首领',
    prepHint: '前排双卫挡刀、中排灵阵首领：深破甲/灵伤破局',
    enemies: [
      {
        name: '灵卫左翼',
        role: 'tank',
        job: 'vanguard',
        slot: 1,
        atk: 17,
        def: 52,
        res: 14,
        maxHp: 235,
        spd: 7,
        tenacityRating: 22,
        fortuneRating: 14,
        skillId: 'mob_smash',
        rank: 'elite',
      },
      {
        name: '灵卫右翼',
        role: 'tank',
        job: 'vanguard',
        slot: 3,
        atk: 17,
        def: 52,
        res: 14,
        maxHp: 235,
        spd: 7,
        tenacityRating: 22,
        fortuneRating: 14,
        skillId: 'mob_smash',
        rank: 'elite',
      },
      {
        name: '灵阵魁首',
        role: 'tank',
        job: 'vanguard',
        slot: 5,
        atk: 21,
        def: 64,
        res: 16,
        maxHp: 460,
        spd: 8,
        tenacityRating: 30,
        fortuneRating: 18,
        skillId: 'mob_guard',
        rank: 'boss',
      },
      {
        name: '灵矢统领',
        role: 'st_burst',
        job: 'mage',
        slot: 8,
        atk: 24,
        def: 8,
        res: 14,
        maxHp: 155,
        spd: 16,
        critRating: 36,
        fortuneRating: 12,
        skillId: 'mob_spirit_bolt',
        rank: 'elite',
      },
    ],
  },
  {
    id: 'boss_shield_stack',
    name: '叠盾首领',
    prepHint: '前排双盾、中排叠盾魁首：对盾增伤/破盾',
    enemies: [
      {
        name: '叠盾甲',
        role: 'tank',
        job: 'vanguard',
        slot: 1,
        atk: 28,
        def: 16,
        res: 12,
        maxHp: 200,
        spd: 10,
        fortuneRating: 10,
        skillId: 'mob_stack_shield',
        startShield: 170,
        shieldPurgeFactor: 0.22,
        rank: 'elite',
      },
      {
        name: '叠盾乙',
        role: 'tank',
        job: 'vanguard',
        slot: 3,
        atk: 28,
        def: 16,
        res: 12,
        maxHp: 200,
        spd: 10,
        fortuneRating: 10,
        skillId: 'mob_stack_shield',
        startShield: 170,
        shieldPurgeFactor: 0.22,
        rank: 'elite',
      },
      {
        name: '叠盾魁首',
        role: 'tank',
        job: 'vanguard',
        slot: 5,
        atk: 34,
        def: 18,
        res: 14,
        maxHp: 310,
        spd: 10,
        fortuneRating: 12,
        skillId: 'mob_stack_shield',
        startShield: 250,
        shieldPurgeFactor: 0.2,
        rank: 'boss',
      },
    ],
  },
  {
    id: 'boss_chaos_rite',
    name: '乱心首领',
    prepHint: '前排祭徒挡刀、中排祭师首领：先断扰再收刀魁',
    enemies: [
      {
        name: '祭徒',
        role: 'st_ctrl',
        job: 'warlock',
        slot: 2,
        atk: 14,
        def: 8,
        res: 9,
        maxHp: 95,
        spd: 13,
        masteryRating: 20,
        fortuneRating: 10,
        skillId: 'mob_berserk',
      },
      {
        name: '乱心魁首',
        role: 'aoe_ctrl',
        job: 'warlock',
        slot: 5,
        atk: 28,
        def: 14,
        res: 18,
        maxHp: 370,
        spd: 15,
        masteryRating: 48,
        fortuneRating: 18,
        skillId: 'mob_chaos_wave',
        rank: 'boss',
      },
      {
        name: '附和者',
        role: 'st_ctrl',
        job: 'warlock',
        slot: 7,
        atk: 17,
        def: 9,
        res: 10,
        maxHp: 110,
        spd: 14,
        masteryRating: 26,
        fortuneRating: 12,
        skillId: 'mob_sleep',
      },
      {
        name: '乱心刀魁',
        role: 'st_burst',
        job: 'assassin',
        slot: 9,
        atk: 22,
        def: 7,
        res: 6,
        maxHp: 135,
        spd: 15,
        critRating: 28,
        fortuneRating: 12,
        skillId: 'mob_arrow',
        rank: 'elite',
      },
    ],
  },
  // —— 主线连战 · 前两波小怪（人数/名目各异；第三波见 chapter/mainlineBattleWaves）——
  {
    id: 'skirmish_wall_foray',
    name: '盾墙斥候',
    prepHint: '轻装斥候：熟悉换位与集火，下一波巡丁更硬',
    maxTurns: 16,
    enemies: [
      {
        name: '盾墙斥候甲',
        role: 'tank',
        job: 'vanguard',
        slot: 1,
        atk: 10,
        def: 12,
        res: 7,
        maxHp: 72,
        spd: 9,
        skillId: 'mob_smash',
      },
      {
        name: '盾墙斥候乙',
        role: 'tank',
        job: 'vanguard',
        slot: 3,
        atk: 10,
        def: 11,
        res: 7,
        maxHp: 68,
        spd: 9,
        skillId: 'mob_smash',
      },
      {
        name: '盾墙斥候丙',
        role: 'st_burst',
        job: 'assassin',
        slot: 9,
        atk: 13,
        def: 6,
        res: 5,
        maxHp: 58,
        spd: 14,
        skillId: 'mob_arrow',
      },
    ],
  },
  {
    id: 'skirmish_wall_pickets',
    name: '盾墙巡丁',
    prepHint: '双巡丁顶前：破甲或群攻尽快清场',
    maxTurns: 16,
    enemies: [
      {
        name: '巡丁·左',
        role: 'tank',
        job: 'vanguard',
        slot: 1,
        atk: 11,
        def: 15,
        res: 8,
        maxHp: 88,
        spd: 8,
        skillId: 'mob_guard',
      },
      {
        name: '巡丁·右',
        role: 'tank',
        job: 'vanguard',
        slot: 3,
        atk: 11,
        def: 14,
        res: 8,
        maxHp: 85,
        spd: 8,
        skillId: 'mob_smash',
      },
    ],
  },
  {
    id: 'skirmish_archers_snipe',
    name: '箭道伏射',
    prepHint: '三弓远点：先护阵或穿透切后',
    maxTurns: 16,
    enemies: [
      {
        name: '伏射弓手甲',
        role: 'st_burst',
        job: 'ranger',
        slot: 7,
        atk: 14,
        def: 4,
        res: 4,
        maxHp: 52,
        spd: 15,
        skillId: 'mob_arrow',
      },
      {
        name: '伏射弓手乙',
        role: 'st_burst',
        job: 'ranger',
        slot: 8,
        atk: 13,
        def: 4,
        res: 4,
        maxHp: 50,
        spd: 15,
        skillId: 'mob_arrow',
      },
      {
        name: '伏射弓手丙',
        role: 'st_burst',
        job: 'ranger',
        slot: 9,
        atk: 13,
        def: 4,
        res: 4,
        maxHp: 48,
        spd: 14,
        skillId: 'mob_arrow',
      },
    ],
  },
  {
    id: 'skirmish_archers_watch',
    name: '箭楼瞭望',
    prepHint: '挡箭杂兵护弓：先破前排再斩弓',
    maxTurns: 16,
    enemies: [
      {
        name: '瞭望杂兵',
        role: 'tank',
        job: 'vanguard',
        slot: 2,
        atk: 10,
        def: 13,
        res: 8,
        maxHp: 78,
        spd: 8,
        skillId: 'mob_smash',
      },
      {
        name: '瞭望弓手',
        role: 'st_burst',
        job: 'ranger',
        slot: 8,
        atk: 15,
        def: 5,
        res: 4,
        maxHp: 55,
        spd: 16,
        skillId: 'mob_arrow',
      },
      {
        name: '瞭望弓手·副',
        role: 'st_burst',
        job: 'ranger',
        slot: 9,
        atk: 14,
        def: 5,
        res: 4,
        maxHp: 52,
        spd: 15,
        skillId: 'mob_arrow',
      },
    ],
  },
  {
    id: 'skirmish_raiders_scouts',
    name: '速攻探子',
    prepHint: '三探子快切：坦阵护后排',
    maxTurns: 16,
    enemies: [
      {
        name: '探子·影',
        role: 'st_burst',
        job: 'assassin',
        slot: 4,
        atk: 14,
        def: 5,
        res: 4,
        maxHp: 62,
        spd: 16,
        skillId: 'mob_arrow',
      },
      {
        name: '探子·风',
        role: 'st_burst',
        job: 'assassin',
        slot: 6,
        atk: 13,
        def: 5,
        res: 4,
        maxHp: 60,
        spd: 16,
        skillId: 'mob_arrow',
      },
      {
        name: '探子·刃',
        role: 'st_burst',
        job: 'assassin',
        slot: 9,
        atk: 15,
        def: 5,
        res: 4,
        maxHp: 58,
        spd: 15,
        skillId: 'mob_arrow',
      },
    ],
  },
  {
    id: 'skirmish_raiders_ctrl',
    name: '速攻控场',
    prepHint: '点穴迟滞连用：解控或秒脆皮',
    maxTurns: 16,
    enemies: [
      {
        name: '迟滞客·小',
        role: 'st_ctrl',
        job: 'warlock',
        slot: 5,
        atk: 12,
        def: 8,
        res: 7,
        maxHp: 72,
        spd: 14,
        masteryRating: 18,
        skillId: 'mob_slow',
      },
      {
        name: '点穴客·小',
        role: 'st_ctrl',
        job: 'warlock',
        slot: 8,
        atk: 12,
        def: 7,
        res: 7,
        maxHp: 70,
        spd: 15,
        masteryRating: 20,
        skillId: 'mob_stun',
      },
    ],
  },
  {
    id: 'skirmish_spirit_motes',
    name: '灵障微光',
    prepHint: '灵卫雏形：物队吃力，备破甲或灵伤',
    maxTurns: 16,
    enemies: [
      {
        name: '灵障微光甲',
        role: 'tank',
        job: 'vanguard',
        slot: 1,
        atk: 11,
        def: 22,
        res: 10,
        maxHp: 82,
        spd: 8,
        skillId: 'mob_smash',
      },
      {
        name: '灵障微光乙',
        role: 'tank',
        job: 'vanguard',
        slot: 3,
        atk: 10,
        def: 20,
        res: 10,
        maxHp: 78,
        spd: 8,
        skillId: 'mob_guard',
      },
      {
        name: '灵矢学徒',
        role: 'st_burst',
        job: 'mage',
        slot: 9,
        atk: 14,
        def: 6,
        res: 10,
        maxHp: 65,
        spd: 14,
        skillId: 'mob_spirit_bolt',
      },
    ],
  },
  {
    id: 'skirmish_spirit_whispers',
    name: '灵障低语',
    prepHint: '双卫一灵矢：持续破甲再收',
    maxTurns: 16,
    enemies: [
      {
        name: '低语灵卫',
        role: 'tank',
        job: 'vanguard',
        slot: 2,
        atk: 12,
        def: 24,
        res: 11,
        maxHp: 95,
        spd: 7,
        skillId: 'mob_guard',
      },
      {
        name: '低语灵弓',
        role: 'st_burst',
        job: 'mage',
        slot: 8,
        atk: 15,
        def: 6,
        res: 11,
        maxHp: 72,
        spd: 15,
        skillId: 'mob_spirit_bolt',
      },
    ],
  },
  {
    id: 'skirmish_chaos_acolytes',
    name: '祭坛侍火',
    prepHint: '侍火者扰乱：优先断控或秒后排',
    maxTurns: 16,
    enemies: [
      {
        name: '侍火者甲',
        role: 'st_ctrl',
        job: 'warlock',
        slot: 4,
        atk: 11,
        def: 7,
        res: 9,
        maxHp: 68,
        spd: 13,
        masteryRating: 16,
        skillId: 'mob_sleep',
      },
      {
        name: '侍火者乙',
        role: 'st_ctrl',
        job: 'warlock',
        slot: 6,
        atk: 11,
        def: 7,
        res: 9,
        maxHp: 66,
        spd: 13,
        masteryRating: 16,
        skillId: 'mob_slow',
      },
      {
        name: '侍火刀客',
        role: 'st_burst',
        job: 'assassin',
        slot: 9,
        atk: 14,
        def: 6,
        res: 6,
        maxHp: 62,
        spd: 14,
        skillId: 'mob_arrow',
      },
    ],
  },
  {
    id: 'skirmish_chaos_candles',
    name: '祭坛烛烟',
    prepHint: '催眠与附和：续航或硬控祭师',
    maxTurns: 16,
    enemies: [
      {
        name: '烛烟祭徒',
        role: 'st_ctrl',
        job: 'warlock',
        slot: 5,
        atk: 12,
        def: 8,
        res: 10,
        maxHp: 75,
        spd: 12,
        masteryRating: 22,
        skillId: 'mob_sleep',
      },
      {
        name: '烛烟刀侍',
        role: 'st_burst',
        job: 'assassin',
        slot: 1,
        atk: 13,
        def: 7,
        res: 6,
        maxHp: 70,
        spd: 13,
        skillId: 'mob_smash',
      },
    ],
  },
  {
    id: 'skirmish_oil_loaders',
    name: '油道搬运',
    prepHint: '油桶杂兵：别让他们拖进治疗节奏',
    maxTurns: 16,
    enemies: [
      {
        name: '油工甲',
        role: 'tank',
        job: 'vanguard',
        slot: 1,
        atk: 10,
        def: 12,
        res: 8,
        maxHp: 80,
        spd: 8,
        skillId: 'mob_smash',
      },
      {
        name: '油工乙',
        role: 'tank',
        job: 'vanguard',
        slot: 3,
        atk: 10,
        def: 11,
        res: 8,
        maxHp: 78,
        spd: 8,
        skillId: 'mob_smash',
      },
      {
        name: '油工医徒',
        role: 'st_heal',
        job: 'healer',
        slot: 9,
        atk: 9,
        def: 6,
        res: 10,
        maxHp: 58,
        spd: 12,
        skillId: 'mob_mend',
      },
    ],
  },
  {
    id: 'skirmish_oil_fumes',
    name: '油阵烟瘴',
    prepHint: '烟瘴中双医：禁疗或穿透点奶',
    maxTurns: 16,
    enemies: [
      {
        name: '烟瘴盾役',
        role: 'tank',
        job: 'vanguard',
        slot: 2,
        atk: 11,
        def: 14,
        res: 9,
        maxHp: 90,
        spd: 8,
        skillId: 'mob_guard',
      },
      {
        name: '烟瘴医士',
        role: 'st_heal',
        job: 'healer',
        slot: 8,
        atk: 10,
        def: 6,
        res: 10,
        maxHp: 62,
        spd: 11,
        skillId: 'mob_mend',
      },
    ],
  },
  {
    id: 'skirmish_shield_trainees',
    name: '叠盾学徒',
    prepHint: '薄盾学徒：对盾增伤或破甲试水',
    maxTurns: 16,
    enemies: [
      {
        name: '叠盾学徒甲',
        role: 'tank',
        job: 'vanguard',
        slot: 1,
        atk: 10,
        def: 13,
        res: 9,
        maxHp: 76,
        spd: 8,
        skillId: 'mob_stack_shield',
        startShield: 60,
        shieldPurgeFactor: 0.35,
      },
      {
        name: '叠盾学徒乙',
        role: 'tank',
        job: 'vanguard',
        slot: 3,
        atk: 10,
        def: 12,
        res: 9,
        maxHp: 74,
        spd: 8,
        skillId: 'mob_stack_shield',
        startShield: 55,
        shieldPurgeFactor: 0.35,
      },
      {
        name: '叠盾学徒丙',
        role: 'tank',
        job: 'vanguard',
        slot: 5,
        atk: 11,
        def: 12,
        res: 9,
        maxHp: 70,
        spd: 9,
        skillId: 'mob_smash',
      },
    ],
  },
  {
    id: 'skirmish_shield_squires',
    name: '叠盾扈从',
    prepHint: '扈从叠盾更厚：破盾后再集火',
    maxTurns: 16,
    enemies: [
      {
        name: '扈从·盾',
        role: 'tank',
        job: 'vanguard',
        slot: 1,
        atk: 11,
        def: 15,
        res: 10,
        maxHp: 92,
        spd: 8,
        skillId: 'mob_stack_shield',
        startShield: 90,
        shieldPurgeFactor: 0.28,
      },
      {
        name: '扈从·刃',
        role: 'st_burst',
        job: 'assassin',
        slot: 9,
        atk: 14,
        def: 6,
        res: 6,
        maxHp: 65,
        spd: 14,
        skillId: 'mob_arrow',
      },
    ],
  },
  {
    id: 'skirmish_warden_pick',
    name: '门前挑阵',
    prepHint: '守门挑阵：热手换位，下一波传功队更硬',
    maxTurns: 16,
    enemies: [
      {
        name: '挑阵关丁甲',
        role: 'tank',
        job: 'vanguard',
        slot: 1,
        atk: 11,
        def: 14,
        res: 8,
        maxHp: 90,
        spd: 8,
        skillId: 'mob_smash',
      },
      {
        name: '挑阵关丁乙',
        role: 'tank',
        job: 'vanguard',
        slot: 3,
        atk: 10,
        def: 13,
        res: 8,
        maxHp: 88,
        spd: 8,
        skillId: 'mob_guard',
      },
    ],
  },
  {
    id: 'skirmish_warden_escort',
    name: '传功扈队',
    prepHint: '传功扈从列阵：守门首领将至',
    maxTurns: 18,
    enemies: [
      {
        name: '传功侧卫甲',
        role: 'tank',
        job: 'vanguard',
        slot: 1,
        atk: 12,
        def: 16,
        res: 10,
        maxHp: 105,
        spd: 8,
        skillId: 'mob_guard',
        rank: 'elite',
      },
      {
        name: '传功侧卫乙',
        role: 'tank',
        job: 'vanguard',
        slot: 3,
        atk: 12,
        def: 15,
        res: 10,
        maxHp: 100,
        spd: 8,
        skillId: 'mob_smash',
      },
      {
        name: '随行医徒',
        role: 'st_heal',
        job: 'healer',
        slot: 9,
        atk: 10,
        def: 6,
        res: 11,
        maxHp: 70,
        spd: 11,
        skillId: 'mob_mend',
      },
    ],
  },
  {
    id: 'skirmish_wall_wedge',
    name: '盾墙侧楔',
    prepHint: '两翼前压、中路留空：注意切后或绕侧',
    maxTurns: 16,
    enemies: [
      { name: '楔锋甲', role: 'tank', job: 'vanguard', slot: 1, atk: 11, def: 13, res: 8, maxHp: 80, spd: 9, skillId: 'mob_smash' },
      { name: '楔锋乙', role: 'tank', job: 'vanguard', slot: 3, atk: 11, def: 13, res: 8, maxHp: 80, spd: 9, skillId: 'mob_guard' },
      { name: '楔锋丙', role: 'st_burst', job: 'assassin', slot: 4, atk: 12, def: 6, res: 5, maxHp: 60, spd: 14, skillId: 'mob_arrow' },
      { name: '楔锋丁', role: 'st_burst', job: 'assassin', slot: 6, atk: 12, def: 6, res: 5, maxHp: 58, spd: 14, skillId: 'mob_arrow' },
    ],
  },
  {
    id: 'skirmish_wall_phalanx',
    name: '盾墙横队',
    prepHint: '四前排横推：群攻或破甲磨穿',
    maxTurns: 16,
    enemies: [
      { name: '横队甲', role: 'tank', job: 'vanguard', slot: 1, atk: 10, def: 14, res: 8, maxHp: 75, spd: 8, skillId: 'mob_smash' },
      { name: '横队乙', role: 'tank', job: 'vanguard', slot: 2, atk: 10, def: 14, res: 8, maxHp: 75, spd: 8, skillId: 'mob_smash' },
      { name: '横队丙', role: 'tank', job: 'vanguard', slot: 3, atk: 10, def: 13, res: 8, maxHp: 72, spd: 8, skillId: 'mob_guard' },
      { name: '横队弓', role: 'st_burst', job: 'ranger', slot: 9, atk: 12, def: 5, res: 4, maxHp: 55, spd: 15, skillId: 'mob_arrow' },
    ],
  },
  {
    id: 'skirmish_wall_rear',
    name: '盾墙后压',
    prepHint: '薄前厚后：穿透或绕后点后排',
    maxTurns: 16,
    enemies: [
      { name: '前哨', role: 'tank', job: 'vanguard', slot: 2, atk: 10, def: 11, res: 7, maxHp: 65, spd: 9, skillId: 'mob_smash' },
      { name: '后阵重盾', role: 'tank', job: 'vanguard', slot: 7, atk: 12, def: 16, res: 9, maxHp: 95, spd: 7, skillId: 'mob_guard' },
      { name: '后阵重盾·副', role: 'tank', job: 'vanguard', slot: 9, atk: 11, def: 15, res: 9, maxHp: 90, spd: 7, skillId: 'mob_smash' },
    ],
  },
  {
    id: 'skirmish_archers_flank',
    name: '箭道侧翼',
    prepHint: '中排双弓 + 前排挡箭：先破挡或直切弓',
    maxTurns: 16,
    enemies: [
      { name: '挡箭卒', role: 'tank', job: 'vanguard', slot: 1, atk: 10, def: 13, res: 8, maxHp: 70, spd: 8, skillId: 'mob_smash' },
      { name: '侧翼弓甲', role: 'st_burst', job: 'ranger', slot: 4, atk: 14, def: 5, res: 4, maxHp: 54, spd: 16, skillId: 'mob_arrow' },
      { name: '侧翼弓乙', role: 'st_burst', job: 'ranger', slot: 6, atk: 14, def: 5, res: 4, maxHp: 52, spd: 16, skillId: 'mob_arrow' },
    ],
  },
  {
    id: 'skirmish_archers_rain',
    name: '箭道箭雨',
    prepHint: '四弓后排齐射：穿透或护阵二选一',
    maxTurns: 16,
    enemies: [
      { name: '箭雨甲', role: 'st_burst', job: 'ranger', slot: 7, atk: 13, def: 4, res: 4, maxHp: 48, spd: 15, skillId: 'mob_arrow' },
      { name: '箭雨乙', role: 'st_burst', job: 'ranger', slot: 8, atk: 13, def: 4, res: 4, maxHp: 48, spd: 15, skillId: 'mob_arrow' },
      { name: '箭雨丙', role: 'st_burst', job: 'ranger', slot: 9, atk: 13, def: 4, res: 4, maxHp: 46, spd: 14, skillId: 'mob_arrow' },
      { name: '箭雨丁', role: 'st_burst', job: 'ranger', slot: 5, atk: 12, def: 5, res: 5, maxHp: 50, spd: 14, skillId: 'mob_arrow' },
    ],
  },
  {
    id: 'skirmish_archers_solo_pair',
    name: '箭道双弓',
    prepHint: '双坦护双弓：集火一侧或穿透',
    maxTurns: 16,
    enemies: [
      { name: '护弓甲', role: 'tank', job: 'vanguard', slot: 1, atk: 10, def: 14, res: 8, maxHp: 78, spd: 8, skillId: 'mob_guard' },
      { name: '护弓乙', role: 'tank', job: 'vanguard', slot: 3, atk: 10, def: 13, res: 8, maxHp: 76, spd: 8, skillId: 'mob_smash' },
      { name: '孤弓甲', role: 'st_burst', job: 'ranger', slot: 7, atk: 15, def: 4, res: 4, maxHp: 56, spd: 16, skillId: 'mob_arrow' },
      { name: '孤弓乙', role: 'st_burst', job: 'ranger', slot: 9, atk: 15, def: 4, res: 4, maxHp: 54, spd: 16, skillId: 'mob_arrow' },
    ],
  },
  {
    id: 'skirmish_raiders_pincer',
    name: '速攻钳击',
    prepHint: '左右中三刺：坦阵缩后排',
    maxTurns: 16,
    enemies: [
      { name: '钳击左', role: 'st_burst', job: 'assassin', slot: 4, atk: 14, def: 5, res: 4, maxHp: 62, spd: 16, skillId: 'mob_arrow' },
      { name: '钳击右', role: 'st_burst', job: 'assassin', slot: 6, atk: 14, def: 5, res: 4, maxHp: 62, spd: 16, skillId: 'mob_arrow' },
      { name: '钳击心', role: 'st_ctrl', job: 'warlock', slot: 5, atk: 12, def: 8, res: 7, maxHp: 70, spd: 15, masteryRating: 18, skillId: 'mob_stun' },
    ],
  },
  {
    id: 'skirmish_raiders_four',
    name: '速攻四刃',
    prepHint: '四散快刀：控场或盾阵护阵',
    maxTurns: 16,
    enemies: [
      { name: '四刃甲', role: 'st_burst', job: 'assassin', slot: 1, atk: 13, def: 5, res: 4, maxHp: 58, spd: 15, skillId: 'mob_arrow' },
      { name: '四刃乙', role: 'st_burst', job: 'assassin', slot: 3, atk: 13, def: 5, res: 4, maxHp: 58, spd: 15, skillId: 'mob_arrow' },
      { name: '四刃丙', role: 'st_burst', job: 'assassin', slot: 7, atk: 13, def: 5, res: 4, maxHp: 56, spd: 15, skillId: 'mob_arrow' },
      { name: '四刃丁', role: 'st_ctrl', job: 'warlock', slot: 9, atk: 12, def: 7, res: 7, maxHp: 68, spd: 14, masteryRating: 16, skillId: 'mob_slow' },
    ],
  },
  {
    id: 'skirmish_spirit_triangle',
    name: '灵障三角',
    prepHint: '三角站位灵卫：破甲或灵伤',
    maxTurns: 16,
    enemies: [
      { name: '三角卫甲', role: 'tank', job: 'vanguard', slot: 1, atk: 11, def: 20, res: 10, maxHp: 78, spd: 8, skillId: 'mob_guard' },
      { name: '三角卫乙', role: 'tank', job: 'vanguard', slot: 5, atk: 11, def: 18, res: 10, maxHp: 74, spd: 8, skillId: 'mob_smash' },
      { name: '三角灵弓', role: 'st_burst', job: 'mage', slot: 9, atk: 14, def: 6, res: 11, maxHp: 68, spd: 14, skillId: 'mob_spirit_bolt' },
    ],
  },
  {
    id: 'skirmish_spirit_line',
    name: '灵障灵线',
    prepHint: '中排灵线四体：持续破甲再收',
    maxTurns: 16,
    enemies: [
      { name: '灵线甲', role: 'tank', job: 'vanguard', slot: 4, atk: 11, def: 19, res: 10, maxHp: 72, spd: 8, skillId: 'mob_smash' },
      { name: '灵线乙', role: 'tank', job: 'vanguard', slot: 5, atk: 11, def: 19, res: 10, maxHp: 72, spd: 8, skillId: 'mob_guard' },
      { name: '灵线丙', role: 'st_burst', job: 'mage', slot: 6, atk: 13, def: 6, res: 11, maxHp: 65, spd: 14, skillId: 'mob_spirit_bolt' },
      { name: '灵线丁', role: 'st_burst', job: 'mage', slot: 8, atk: 13, def: 6, res: 11, maxHp: 63, spd: 14, skillId: 'mob_spirit_bolt' },
    ],
  },
  {
    id: 'skirmish_chaos_ring',
    name: '祭坛环阵',
    prepHint: '环状控场：断控或秒脆皮',
    maxTurns: 16,
    enemies: [
      { name: '环祭甲', role: 'st_ctrl', job: 'warlock', slot: 4, atk: 11, def: 7, res: 9, maxHp: 66, spd: 13, masteryRating: 16, skillId: 'mob_sleep' },
      { name: '环祭乙', role: 'st_ctrl', job: 'warlock', slot: 6, atk: 11, def: 7, res: 9, maxHp: 66, spd: 13, masteryRating: 16, skillId: 'mob_slow' },
      { name: '环祭丙', role: 'st_ctrl', job: 'warlock', slot: 8, atk: 11, def: 7, res: 9, maxHp: 64, spd: 12, masteryRating: 16, skillId: 'mob_sleep' },
      { name: '环刃', role: 'st_burst', job: 'assassin', slot: 2, atk: 13, def: 6, res: 6, maxHp: 60, spd: 14, skillId: 'mob_smash' },
    ],
  },
  {
    id: 'skirmish_chaos_split',
    name: '祭坛分祭',
    prepHint: '前后分祭：先清控场',
    maxTurns: 16,
    enemies: [
      { name: '前祭刀', role: 'st_burst', job: 'assassin', slot: 1, atk: 12, def: 7, res: 6, maxHp: 68, spd: 13, skillId: 'mob_smash' },
      { name: '后祭眠', role: 'st_ctrl', job: 'warlock', slot: 9, atk: 12, def: 8, res: 10, maxHp: 72, spd: 12, masteryRating: 20, skillId: 'mob_sleep' },
      { name: '后祭迟', role: 'st_ctrl', job: 'warlock', slot: 7, atk: 11, def: 8, res: 10, maxHp: 70, spd: 12, masteryRating: 18, skillId: 'mob_slow' },
    ],
  },
  {
    id: 'skirmish_oil_spill',
    name: '油道泼油',
    prepHint: '双工泼油 + 侧翼：禁疗或快杀',
    maxTurns: 16,
    enemies: [
      { name: '泼油甲', role: 'tank', job: 'vanguard', slot: 1, atk: 10, def: 12, res: 8, maxHp: 76, spd: 8, skillId: 'mob_smash' },
      { name: '泼油乙', role: 'tank', job: 'vanguard', slot: 3, atk: 10, def: 11, res: 8, maxHp: 74, spd: 8, skillId: 'mob_smash' },
      { name: '泼油医', role: 'st_heal', job: 'healer', slot: 8, atk: 9, def: 6, res: 10, maxHp: 56, spd: 11, skillId: 'mob_mend' },
      { name: '泼油刃', role: 'st_burst', job: 'assassin', slot: 9, atk: 12, def: 6, res: 6, maxHp: 58, spd: 14, skillId: 'mob_arrow' },
    ],
  },
  {
    id: 'skirmish_oil_twin_heal',
    name: '油道双医',
    prepHint: '双医分居后排：穿透点奶',
    maxTurns: 16,
    enemies: [
      { name: '油盾', role: 'tank', job: 'vanguard', slot: 2, atk: 11, def: 14, res: 9, maxHp: 88, spd: 8, skillId: 'mob_guard' },
      { name: '医徒甲', role: 'st_heal', job: 'healer', slot: 7, atk: 9, def: 6, res: 10, maxHp: 55, spd: 11, skillId: 'mob_mend' },
      { name: '医徒乙', role: 'st_heal', job: 'healer', slot: 9, atk: 9, def: 6, res: 10, maxHp: 55, spd: 11, skillId: 'mob_mend' },
    ],
  },
  {
    id: 'skirmish_shield_arc',
    name: '叠盾弧阵',
    prepHint: '弧阵三盾：对盾增伤破开',
    maxTurns: 16,
    enemies: [
      { name: '弧盾甲', role: 'tank', job: 'vanguard', slot: 1, atk: 10, def: 12, res: 9, maxHp: 70, spd: 8, skillId: 'mob_stack_shield', startShield: 50, shieldPurgeFactor: 0.35 },
      { name: '弧盾乙', role: 'tank', job: 'vanguard', slot: 2, atk: 10, def: 12, res: 9, maxHp: 68, spd: 8, skillId: 'mob_stack_shield', startShield: 45, shieldPurgeFactor: 0.35 },
      { name: '弧盾丙', role: 'tank', job: 'vanguard', slot: 3, atk: 10, def: 12, res: 9, maxHp: 68, spd: 8, skillId: 'mob_stack_shield', startShield: 45, shieldPurgeFactor: 0.35 },
      { name: '弧刃', role: 'st_burst', job: 'assassin', slot: 9, atk: 12, def: 6, res: 6, maxHp: 58, spd: 14, skillId: 'mob_arrow' },
    ],
  },
  {
    id: 'skirmish_shield_core',
    name: '叠盾盾心',
    prepHint: '中排厚盾核心 + 两翼：先破心',
    maxTurns: 16,
    enemies: [
      { name: '盾心', role: 'tank', job: 'vanguard', slot: 5, atk: 11, def: 14, res: 10, maxHp: 88, spd: 8, skillId: 'mob_stack_shield', startShield: 80, shieldPurgeFactor: 0.3 },
      { name: '盾翼甲', role: 'tank', job: 'vanguard', slot: 4, atk: 10, def: 12, res: 9, maxHp: 72, spd: 9, skillId: 'mob_smash' },
      { name: '盾翼乙', role: 'tank', job: 'vanguard', slot: 6, atk: 10, def: 12, res: 9, maxHp: 72, spd: 9, skillId: 'mob_smash' },
    ],
  },
];

export const ENCOUNTERS: EncounterDef[] = [
  ...BASE_ENCOUNTERS,
  ...MAINLINE_BIOME_ENCOUNTERS,
  ...MAINLINE_CAP_BLEND_ENCOUNTERS,
];
