import type { GridSlot, Role, UnitRank, UnitTemplate } from '../shared/types.js';

export interface EnemySpec {
  name: string;
  role: Role;
  job: UnitTemplate['job'];
  slot: GridSlot;
  physAtk: number;
  spiritAtk: number;
  physDef: number;
  spiritDef: number;
  maxHp: number;
  spd: number;
  critRating?: number;
  critDmgRating?: number;
  hasteRating?: number;
  versRating?: number;
  masteryRating?: number;
  finalDmgRating?: number;
  fortune?: number;
  skillId: string;
  /** 抗控分级，默认 normal */
  rank?: UnitRank;
}

export interface EncounterDef {
  id: string;
  name: string;
  enemies: EnemySpec[];
}

/** 三套路轮换，逼换阵（2026-08-01 加压：开局队不应 100% 秒过） */
export const ENCOUNTERS: EncounterDef[] = [
  {
    id: 'wall',
    name: '盾墙巡逻',
    enemies: [
      {
        name: '铁壁恶徒',
        role: 'tank',
        job: 'vanguard',
        slot: 1,
        physAtk: 14,
        spiritAtk: 8,
        physDef: 22,
        spiritDef: 16,
        maxHp: 145,
        spd: 7,
        versRating: 18,
        fortune: 10,
        skillId: 'mob_guard',
        rank: 'elite',
      },
      {
        name: '厚甲恶徒',
        role: 'tank',
        job: 'vanguard',
        slot: 3,
        physAtk: 13,
        spiritAtk: 8,
        physDef: 20,
        spiritDef: 15,
        maxHp: 135,
        spd: 7,
        versRating: 14,
        fortune: 10,
        skillId: 'mob_smash',
      },
      {
        name: '封脉刀手',
        role: 'st_ctrl',
        job: 'warlock',
        slot: 5,
        physAtk: 13,
        spiritAtk: 11,
        physDef: 9,
        spiritDef: 8,
        maxHp: 78,
        spd: 11,
        masteryRating: 24,
        fortune: 8,
        skillId: 'mob_heal_block',
      },
    ],
  },
  {
    id: 'archers',
    name: '后排伏击',
    enemies: [
      {
        name: '挡箭杂兵',
        role: 'tank',
        job: 'vanguard',
        slot: 2,
        physAtk: 11,
        spiritAtk: 7,
        physDef: 12,
        spiritDef: 9,
        maxHp: 95,
        spd: 8,
        skillId: 'mob_smash',
      },
      {
        name: '伏击弓手甲',
        role: 'st_burst',
        job: 'ranger',
        slot: 7,
        physAtk: 19,
        spiritAtk: 12,
        physDef: 4,
        spiritDef: 3,
        maxHp: 68,
        spd: 14,
        critRating: 26,
        critDmgRating: 20,
        skillId: 'mob_arrow',
      },
      {
        name: '伏击弓手乙',
        role: 'st_burst',
        job: 'ranger',
        slot: 9,
        physAtk: 18,
        spiritAtk: 12,
        physDef: 4,
        spiritDef: 3,
        maxHp: 64,
        spd: 15,
        critRating: 26,
        critDmgRating: 20,
        skillId: 'mob_arrow',
      },
    ],
  },
  {
    id: 'raiders',
    name: '速攻刺客',
    enemies: [
      {
        name: '点穴客',
        role: 'st_ctrl',
        job: 'warlock',
        slot: 5,
        physAtk: 13,
        spiritAtk: 10,
        physDef: 6,
        spiritDef: 5,
        maxHp: 62,
        spd: 16,
        masteryRating: 26,
        fortune: 6,
        skillId: 'mob_stun',
      },
      {
        name: '迟滞客',
        role: 'st_ctrl',
        job: 'warlock',
        slot: 4,
        physAtk: 12,
        spiritAtk: 9,
        physDef: 6,
        spiritDef: 5,
        maxHp: 58,
        spd: 15,
        masteryRating: 20,
        fortune: 6,
        skillId: 'mob_slow',
      },
      {
        name: '催眠客',
        role: 'st_ctrl',
        job: 'warlock',
        slot: 8,
        physAtk: 13,
        spiritAtk: 10,
        physDef: 5,
        spiritDef: 4,
        maxHp: 55,
        spd: 14,
        masteryRating: 22,
        fortune: 5,
        skillId: 'mob_sleep',
      },
      {
        name: '煽狂客',
        role: 'st_ctrl',
        job: 'warlock',
        slot: 6,
        physAtk: 12,
        spiritAtk: 9,
        physDef: 5,
        spiritDef: 4,
        maxHp: 52,
        spd: 13,
        masteryRating: 20,
        fortune: 5,
        skillId: 'mob_berserk',
      },
      {
        name: '影刃',
        role: 'st_burst',
        job: 'assassin',
        slot: 9,
        physAtk: 16,
        spiritAtk: 11,
        physDef: 4,
        spiritDef: 3,
        maxHp: 58,
        spd: 16,
        critRating: 26,
        critDmgRating: 18,
        fortune: 5,
        skillId: 'mob_arrow',
      },
    ],
  },
  {
    id: 'spirit_wall',
    name: '灵防结阵',
    enemies: [
      {
        name: '灵甲卫',
        role: 'tank',
        job: 'vanguard',
        slot: 1,
        physAtk: 12,
        spiritAtk: 14,
        physDef: 16,
        spiritDef: 26,
        maxHp: 165,
        spd: 7,
        versRating: 18,
        skillId: 'mob_guard',
        rank: 'elite',
      },
      {
        name: '灵甲卫乙',
        role: 'tank',
        job: 'vanguard',
        slot: 3,
        physAtk: 13,
        spiritAtk: 14,
        physDef: 15,
        spiritDef: 24,
        maxHp: 155,
        spd: 7,
        skillId: 'mob_smash',
      },
      {
        name: '灵矢手',
        role: 'st_burst',
        job: 'mage',
        slot: 8,
        physAtk: 9,
        spiritAtk: 22,
        physDef: 5,
        spiritDef: 10,
        maxHp: 72,
        spd: 14,
        critRating: 24,
        skillId: 'mob_spirit_bolt',
      },
    ],
  },
  {
    id: 'chaos_rite',
    name: '乱心仪式',
    enemies: [
      {
        name: '乱心祭师',
        role: 'aoe_ctrl',
        job: 'warlock',
        slot: 5,
        physAtk: 10,
        spiritAtk: 17,
        physDef: 8,
        spiritDef: 12,
        maxHp: 125,
        spd: 12,
        masteryRating: 32,
        skillId: 'mob_chaos_wave',
        rank: 'elite',
      },
      {
        name: '附和者',
        role: 'st_ctrl',
        job: 'warlock',
        slot: 4,
        physAtk: 12,
        spiritAtk: 13,
        physDef: 6,
        spiritDef: 7,
        maxHp: 70,
        spd: 14,
        skillId: 'mob_berserk',
      },
      {
        name: '附和者乙',
        role: 'st_ctrl',
        job: 'warlock',
        slot: 6,
        physAtk: 12,
        spiritAtk: 13,
        physDef: 6,
        spiritDef: 7,
        maxHp: 70,
        spd: 14,
        skillId: 'mob_sleep',
      },
    ],
  },
  {
    id: 'boss_warden',
    name: '守卫首领',
    enemies: [
      {
        name: '镇狱守卫',
        role: 'tank',
        job: 'vanguard',
        slot: 2,
        physAtk: 17,
        spiritAtk: 11,
        physDef: 22,
        spiritDef: 17,
        maxHp: 250,
        spd: 9,
        versRating: 22,
        masteryRating: 20,
        skillId: 'mob_boss_slam',
        rank: 'boss',
      },
      {
        name: '侧卫甲',
        role: 'st_burst',
        job: 'assassin',
        slot: 7,
        physAtk: 17,
        spiritAtk: 9,
        physDef: 5,
        spiritDef: 4,
        maxHp: 68,
        spd: 15,
        critRating: 28,
        skillId: 'mob_arrow',
      },
      {
        name: '侧卫乙',
        role: 'st_heal',
        job: 'healer',
        slot: 9,
        physAtk: 5,
        spiritAtk: 14,
        physDef: 7,
        spiritDef: 11,
        maxHp: 75,
        spd: 11,
        masteryRating: 22,
        skillId: 'mob_heal_block',
      },
    ],
  },
];
