import type { SkillDef } from '../shared/types.js';

export const SKILLS: Record<string, SkillDef> = {
  skill_hero_strike: {
    id: 'skill_hero_strike',
    name: '斩击',
    nameKey: 'skill.hero_strike',
    targetPattern: 'single',
    tags: ['damage', 'purge'],
    multiplier: 1.9,
    qiCost: 50,
    applyStatus: [],
    effects: [{ kind: 'purge' }],
    damageSchool: 'phys',
    aiWeight: 0.55,
  },
  skill_zhangfei_roar: {
    id: 'skill_zhangfei_roar',
    name: '咆哮',
    nameKey: 'skill.zhangfei_roar',
    targetPattern: 'single',
    tags: ['damage'],
    multiplier: 0.85,
    qiCost: 45,
    applyStatus: [{ statusId: 'stun', duration: 1 }],
    damageSchool: 'phys',
    aiWeight: 0.5,
  },
  skill_zhaoyun_longdan: {
    id: 'skill_zhaoyun_longdan',
    name: '龙胆',
    nameKey: 'skill.zhaoyun_longdan',
    targetPattern: 'single',
    tags: ['pierce', 'damage'],
    multiplier: 2.05,
    qiCost: 55,
    applyStatus: [{ statusId: 'bleed', duration: 3, layers: 1 }],
    damageSchool: 'phys',
    aiWeight: 0.65,
  },
  skill_wukong_sweep: {
    id: 'skill_wukong_sweep',
    name: '金箍扫',
    nameKey: 'skill.wukong_sweep',
    targetPattern: 'row_front',
    tags: ['aoe', 'damage'],
    multiplier: 1.2,
    qiCost: 55,
    applyStatus: [],
    damageSchool: 'phys',
    aiWeight: 0.6,
  },
  skill_huatuo_qingnang: {
    id: 'skill_huatuo_qingnang',
    name: '青囊',
    nameKey: 'skill.huatuo_qingnang',
    targetPattern: 'single',
    tags: ['heal', 'cleanse'],
    multiplier: 1.4,
    qiCost: 45,
    applyStatus: [],
    effects: [{ kind: 'cleanse' }],
    damageSchool: 'spirit',
    aiWeight: 0.75,
  },
  skill_houyi_luori: {
    id: 'skill_houyi_luori',
    name: '落日',
    nameKey: 'skill.houyi_luori',
    targetPattern: 'single',
    tags: ['pierce', 'damage'],
    multiplier: 2.0,
    qiCost: 55,
    applyStatus: [],
    damageSchool: 'phys',
    focusPolicy: 'lowest_hp',
    aiWeight: 0.65,
  },
  skill_heracles_hide: {
    id: 'skill_heracles_hide',
    name: '狮皮',
    nameKey: 'skill.heracles_hide',
    targetPattern: 'single',
    tags: ['guard'],
    multiplier: 1.25,
    qiCost: 45,
    applyStatus: [{ statusId: 'shield', duration: 99, value: 1 }],
    damageSchool: 'phys',
    aiWeight: 0.5,
  },
  skill_zhuge_qimen: {
    id: 'skill_zhuge_qimen',
    name: '奇门',
    nameKey: 'skill.zhuge_qimen',
    targetPattern: 'single',
    tags: ['damage'],
    multiplier: 0.55,
    qiCost: 50,
    applyStatus: [{ statusId: 'shred', duration: 2, value: 0.75 }],
    damageSchool: 'spirit',
    aiWeight: 0.55,
  },
  skill_baigujing_huagu: {
    id: 'skill_baigujing_huagu',
    name: '化骨',
    nameKey: 'skill.baigujing_huagu',
    targetPattern: 'row_front',
    tags: ['aoe', 'damage'],
    multiplier: 0.7,
    qiCost: 50,
    applyStatus: [{ statusId: 'havoc', duration: 1 }],
    damageSchool: 'spirit',
    aiWeight: 0.55,
  },
  skill_medusa_gaze: {
    id: 'skill_medusa_gaze',
    name: '石化',
    nameKey: 'skill.medusa_gaze',
    targetPattern: 'single',
    tags: ['damage'],
    multiplier: 0.55,
    qiCost: 50,
    applyStatus: [{ statusId: 'stun', duration: 1 }],
    damageSchool: 'spirit',
    aiWeight: 0.55,
  },
  skill_athena_aegis: {
    id: 'skill_athena_aegis',
    name: '神恩',
    nameKey: 'skill.athena_aegis',
    targetPattern: 'all',
    tags: ['heal', 'aoe'],
    multiplier: 0.8,
    qiCost: 50,
    applyStatus: [],
    damageSchool: 'spirit',
    aiWeight: 0.7,
  },

  // —— 敌方 ——
  mob_smash: {
    id: 'mob_smash',
    name: '重击',
    targetPattern: 'single',
    tags: ['damage'],
    multiplier: 1.4,
    qiCost: 45,
    applyStatus: [],
    damageSchool: 'phys',
    aiWeight: 0.5,
  },
  mob_arrow: {
    id: 'mob_arrow',
    name: '穿杨',
    targetPattern: 'single',
    tags: ['pierce', 'damage'],
    multiplier: 1.7,
    qiCost: 50,
    applyStatus: [],
    damageSchool: 'phys',
    aiWeight: 0.7,
  },
  mob_stun: {
    id: 'mob_stun',
    name: '点穴',
    targetPattern: 'single',
    tags: ['damage'],
    multiplier: 0.6,
    qiCost: 50,
    applyStatus: [{ statusId: 'stun', duration: 1 }],
    damageSchool: 'phys',
    aiWeight: 0.45,
  },
  mob_guard: {
    id: 'mob_guard',
    name: '铁壁',
    targetPattern: 'single',
    tags: ['guard'],
    multiplier: 1.0,
    qiCost: 40,
    applyStatus: [{ statusId: 'shield', duration: 99, value: 1 }],
    damageSchool: 'spirit',
    aiWeight: 0.4,
  },
  mob_heal_block: {
    id: 'mob_heal_block',
    name: '封脉',
    targetPattern: 'single',
    tags: ['damage'],
    multiplier: 0.8,
    qiCost: 50,
    applyStatus: [{ statusId: 'heal_block', duration: 2 }],
    damageSchool: 'spirit',
    aiWeight: 0.5,
  },
  mob_slow: {
    id: 'mob_slow',
    name: '迟滞',
    targetPattern: 'single',
    tags: ['damage'],
    multiplier: 0.7,
    qiCost: 45,
    applyStatus: [{ statusId: 'slow', duration: 2 }],
    damageSchool: 'spirit',
    aiWeight: 0.5,
  },
  mob_sleep: {
    id: 'mob_sleep',
    name: '催眠',
    targetPattern: 'single',
    tags: ['damage'],
    multiplier: 0.4,
    qiCost: 50,
    applyStatus: [{ statusId: 'sleep', duration: 2 }],
    damageSchool: 'spirit',
    aiWeight: 0.4,
  },
  mob_berserk: {
    id: 'mob_berserk',
    name: '煽狂',
    targetPattern: 'single',
    tags: ['damage'],
    multiplier: 0.5,
    qiCost: 50,
    applyStatus: [{ statusId: 'berserk', duration: 2 }],
    damageSchool: 'spirit',
    aiWeight: 0.35,
  },
};

export function getSkill(id: string): SkillDef {
  const skill = SKILLS[id];
  if (!skill) throw new Error(`Unknown skill: ${id}`);
  return {
    ...skill,
    applyStatus: skill.applyStatus.map((s) => ({ ...s })),
    tags: [...skill.tags],
    effects: skill.effects?.map((e) => ({ ...e })),
  };
}
