import type { SkillDef } from '../shared/types.js';
import { DEEP_SKILL_OVERRIDES } from './deepKits.js';
import { EXPAND_SKILLS } from './roster/buildExpand.js';

const CORE_SKILLS_BASE: Record<string, SkillDef> = {
  skill_hero_strike: {
    id: 'skill_hero_strike',
    name: '斩击',
    nameKey: 'skill.hero_strike',
    targetPattern: 'single',
    tags: ['damage', 'purge'],
    multiplier: 1.9,
    qiCost: 50,
    applyStatus: [],
    effects: [{ kind: 'purge' }],
    damageSchool: 'phys',
    aiWeight: 0.55,
  },
  skill_zhangfei_roar: {
    id: 'skill_zhangfei_roar',
    name: '咆哮',
    nameKey: 'skill.zhangfei_roar',
    targetPattern: 'single',
    tags: ['damage'],
    /** 当阳断喝：先声夺人；星章开结界/还元；硬控带 ≥1.05 */
    multiplier: 1.15,
    qiCost: 45,
    applyStatus: [{ statusId: 'stun', duration: 1 }],
    effects: [{ kind: 'first_cast', multiplier: 1.4 }],
    damageSchool: 'phys',
    aiWeight: 0.5,
  },
  skill_zhaoyun_longdan: {
    id: 'skill_zhaoyun_longdan',
    name: '龙胆',
    nameKey: 'skill.zhaoyun_longdan',
    targetPattern: 'single',
    tags: ['pierce', 'damage'],
    /** 穿后排点杀；星章开猎印/斩杀/还元 */
    multiplier: 2.05,
    qiCost: 55,
    applyStatus: [{ statusId: 'bleed', duration: 3, layers: 1 }],
    effects: [{ kind: 'vs_shield', multiplier: 1.25 }],
    damageSchool: 'phys',
    aiWeight: 0.65,
  },
  skill_wukong_sweep: {
    id: 'skill_wukong_sweep',
    name: '金箍扫',
    nameKey: 'skill.wukong_sweep',
    targetPattern: 'row_front',
    tags: ['aoe', 'damage'],
    multiplier: 1.15,
    qiCost: 55,
    applyStatus: [{ statusId: 'stun', duration: 1 }],
    effects: [{ kind: 'surround', multiplier: 1.2 }],
    damageSchool: 'phys',
    aiWeight: 0.6,
  },
  skill_huatuo_qingnang: {
    id: 'skill_huatuo_qingnang',
    name: '青囊',
    nameKey: 'skill.huatuo_qingnang',
    targetPattern: 'single',
    tags: ['heal', 'cleanse'],
    /** 妙手回春；星章开残血加疗/回能 */
    multiplier: 1.4,
    qiCost: 45,
    applyStatus: [],
    effects: [
      { kind: 'cleanse' },
      { kind: 'heal_low_hp', value: 0.4, multiplier: 1.35 },
    ],
    damageSchool: 'spirit',
    aiWeight: 0.75,
  },
  skill_houyi_luori: {
    id: 'skill_houyi_luori',
    name: '落日',
    nameKey: 'skill.houyi_luori',
    targetPattern: 'single',
    tags: ['pierce', 'damage'],
    multiplier: 1.95,
    qiCost: 55,
    /** 穿后排 + 点残血 + 流血，对弓手阵有解法感 */
    applyStatus: [{ statusId: 'bleed', duration: 3, layers: 1 }],
    damageSchool: 'phys',
    focusPolicy: 'lowest_hp',
    aiWeight: 0.65,
  },
  skill_zhuge_qimen: {
    id: 'skill_zhuge_qimen',
    name: '奇门',
    nameKey: 'skill.zhuge_qimen',
    targetPattern: 'single',
    tags: ['damage'],
    multiplier: 0.95,
    qiCost: 50,
    applyStatus: [{ statusId: 'qi_drought', duration: 2 }, { statusId: 'slow', duration: 2 }],
    effects: [{ kind: 'ally_grant_qi', value: 16 }],
    damageSchool: 'spirit',
    aiWeight: 0.55,
  },
  skill_baigujing_huagu: {
    id: 'skill_baigujing_huagu',
    name: '化骨',
    nameKey: 'skill.baigujing_huagu',
    targetPattern: 'row_front',
    tags: ['aoe', 'damage'],
    /** 群控硬控带；每人系数 */
    multiplier: 1.1,
    qiCost: 50,
    applyStatus: [{ statusId: 'havoc', duration: 1 }],
    damageSchool: 'spirit',
    aiWeight: 0.55,
  },

  // —— +10 公版 ——
  skill_guanyu_slash: {
    id: 'skill_guanyu_slash',
    name: '青龙斩',
    nameKey: 'skill.guanyu_slash',
    targetPattern: 'single',
    tags: ['damage'],
    multiplier: 1.85,
    qiCost: 50,
    applyStatus: [{ statusId: 'bleed', duration: 3, layers: 1 }],
    damageSchool: 'phys',
    aiWeight: 0.6,
  },
  skill_lvbu_wushuang: {
    id: 'skill_lvbu_wushuang',
    name: '无双',
    nameKey: 'skill.lvbu_wushuang',
    targetPattern: 'single',
    tags: ['damage'],
    multiplier: 2.25,
    qiCost: 60,
    applyStatus: [],
    damageSchool: 'phys',
    aiWeight: 0.7,
  },
  skill_dianwei_guard: {
    id: 'skill_dianwei_guard',
    name: '恶来盾',
    nameKey: 'skill.dianwei_guard',
    targetPattern: 'single',
    tags: ['guard'],
    multiplier: 1.35,
    qiCost: 45,
    applyStatus: [{ statusId: 'shield', duration: 99, value: 1 }],
    damageSchool: 'phys',
    aiWeight: 0.5,
  },
  skill_nezha_arms: {
    id: 'skill_nezha_arms',
    name: '火尖枪',
    nameKey: 'skill.nezha_arms',
    targetPattern: 'single',
    tags: ['pierce', 'damage'],
    multiplier: 1.7,
    qiCost: 50,
    /** 穿甲灼锋：与赵云流血 / 后羿点残错开 */
    applyStatus: [{ statusId: 'bleed', duration: 2, layers: 1 }],
    damageSchool: 'phys',
    aiWeight: 0.65,
  },
  skill_daji_charm: {
    id: 'skill_daji_charm',
    name: '狐媚',
    nameKey: 'skill.daji_charm',
    targetPattern: 'row_front',
    tags: ['aoe', 'damage'],
    multiplier: 1.1,
    qiCost: 50,
    applyStatus: [{ statusId: 'havoc', duration: 1 }],
    damageSchool: 'spirit',
    aiWeight: 0.55,
  },
  skill_yangjian_blade: {
    id: 'skill_yangjian_blade',
    name: '三尖两刃',
    nameKey: 'skill.yangjian_blade',
    targetPattern: 'single',
    tags: ['pierce', 'damage'],
    multiplier: 2.0,
    qiCost: 55,
    applyStatus: [{ statusId: 'bleed', duration: 3, layers: 1 }],
    damageSchool: 'phys',
    focusPolicy: 'lowest_hp',
    aiWeight: 0.65,
  },
  skill_change_moon: {
    id: 'skill_change_moon',
    name: '月华',
    nameKey: 'skill.change_moon',
    targetPattern: 'all',
    tags: ['heal', 'aoe'],
    multiplier: 0.75,
    qiCost: 50,
    applyStatus: [],
    effects: [{ kind: 'cleanse' }],
    damageSchool: 'spirit',
    aiWeight: 0.7,
  },
  skill_xishi_chenyu: {
    id: 'skill_xishi_chenyu',
    name: '沉鱼',
    nameKey: 'skill.xishi_chenyu',
    targetPattern: 'single',
    tags: ['damage'],
    /** 硬控沉眠带 ≥1.05 */
    multiplier: 1.1,
    qiCost: 50,
    applyStatus: [{ statusId: 'sleep', duration: 2 }],
    damageSchool: 'spirit',
    aiWeight: 0.5,
  },
  skill_sunbin_jianzao: {
    id: 'skill_sunbin_jianzao',
    name: '减灶',
    nameKey: 'skill.sunbin_jianzao',
    targetPattern: 'single',
    tags: ['damage'],
    multiplier: 0.45,
    qiCost: 48,
    applyStatus: [
      { statusId: 'shred', duration: 2, value: 0.72 },
      { statusId: 'slow', duration: 2 },
    ],
    damageSchool: 'spirit',
    aiWeight: 0.55,
  },

  // —— 敌方 ——
  mob_spirit_bolt: {
    id: 'mob_spirit_bolt',
    name: '灵矢',
    targetPattern: 'single',
    tags: ['pierce', 'damage'],
    multiplier: 1.6,
    qiCost: 50,
    applyStatus: [],
    damageSchool: 'spirit',
    aiWeight: 0.65,
  },
  mob_chaos_wave: {
    id: 'mob_chaos_wave',
    name: '乱心',
    targetPattern: 'row_front',
    tags: ['aoe', 'damage'],
    multiplier: 0.65,
    qiCost: 55,
    applyStatus: [{ statusId: 'havoc', duration: 1 }],
    damageSchool: 'spirit',
    aiWeight: 0.5,
  },
  mob_boss_slam: {
    id: 'mob_boss_slam',
    name: '镇压',
    targetPattern: 'single',
    tags: ['damage'],
    multiplier: 1.8,
    qiCost: 50,
    applyStatus: [{ statusId: 'stun', duration: 1 }],
    damageSchool: 'phys',
    aiWeight: 0.55,
  },

  mob_smash: {
    id: 'mob_smash',
    name: '重击',
    targetPattern: 'single',
    tags: ['damage'],
    multiplier: 1.45,
    qiCost: 45,
    applyStatus: [{ statusId: 'shred', duration: 2, value: 0.88 }],
    damageSchool: 'phys',
    aiWeight: 0.5,
  },
  mob_arrow: {
    id: 'mob_arrow',
    name: '穿杨',
    targetPattern: 'single',
    tags: ['pierce', 'damage'],
    multiplier: 1.85,
    qiCost: 50,
    applyStatus: [{ statusId: 'bleed', duration: 2, layers: 1 }],
    damageSchool: 'phys',
    aiWeight: 0.7,
  },
  mob_stun: {
    id: 'mob_stun',
    name: '点穴',
    targetPattern: 'single',
    tags: ['damage'],
    multiplier: 0.6,
    qiCost: 50,
    applyStatus: [{ statusId: 'stun', duration: 1 }],
    damageSchool: 'phys',
    aiWeight: 0.45,
  },
  mob_guard: {
    id: 'mob_guard',
    name: '铁壁',
    targetPattern: 'single',
    tags: ['guard'],
    multiplier: 1.0,
    qiCost: 40,
    applyStatus: [{ statusId: 'shield', duration: 99, value: 1 }],
    damageSchool: 'spirit',
    aiWeight: 0.4,
  },
  mob_mend: {
    id: 'mob_mend',
    name: '续命',
    targetPattern: 'single',
    tags: ['heal'],
    multiplier: 1.85,
    qiCost: 22,
    applyStatus: [],
    effects: [{ kind: 'heal_low_hp', value: 0.55, multiplier: 1.75 }],
    damageSchool: 'spirit',
    aiWeight: 0.95,
  },
  mob_stack_shield: {
    id: 'mob_stack_shield',
    name: '叠盾',
    targetPattern: 'single',
    tags: ['guard', 'sustain'],
    multiplier: 3.1,
    qiCost: 24,
    applyStatus: [{ statusId: 'shield', duration: 99, value: 1 }],
    damageSchool: 'spirit',
    aiWeight: 0.92,
  },
  mob_heal_block: {
    id: 'mob_heal_block',
    name: '封脉',
    targetPattern: 'single',
    tags: ['damage'],
    multiplier: 0.8,
    qiCost: 50,
    applyStatus: [{ statusId: 'heal_block', duration: 2 }],
    damageSchool: 'spirit',
    aiWeight: 0.5,
  },
  mob_slow: {
    id: 'mob_slow',
    name: '迟滞',
    targetPattern: 'single',
    tags: ['damage'],
    multiplier: 0.7,
    qiCost: 45,
    applyStatus: [{ statusId: 'slow', duration: 2 }],
    damageSchool: 'spirit',
    aiWeight: 0.5,
  },
  mob_sleep: {
    id: 'mob_sleep',
    name: '催眠',
    targetPattern: 'single',
    tags: ['damage'],
    multiplier: 0.4,
    qiCost: 50,
    applyStatus: [{ statusId: 'sleep', duration: 2 }],
    damageSchool: 'spirit',
    aiWeight: 0.4,
  },
  mob_berserk: {
    id: 'mob_berserk',
    name: '煽狂',
    targetPattern: 'single',
    tags: ['damage'],
    multiplier: 0.5,
    qiCost: 50,
    applyStatus: [{ statusId: 'berserk', duration: 2 }],
    damageSchool: 'spirit',
    aiWeight: 0.35,
  },
};

function applyDeepOverrides(base: Record<string, SkillDef>): Record<string, SkillDef> {
  const out: Record<string, SkillDef> = { ...base };
  for (const [id, patch] of Object.entries(DEEP_SKILL_OVERRIDES)) {
    const cur = out[id];
    if (!cur) continue;
    out[id] = {
      ...cur,
      ...patch,
      applyStatus: (patch.applyStatus ?? cur.applyStatus).map((s) => ({ ...s })),
      tags: [...(patch.tags ?? cur.tags)],
      effects: (patch.effects ?? cur.effects)?.map((e) => ({ ...e })),
    };
  }
  return out;
}

export const SKILLS: Record<string, SkillDef> = applyDeepOverrides({
  ...CORE_SKILLS_BASE,
  ...EXPAND_SKILLS,
});

export function getSkill(id: string): SkillDef {
  const skill = SKILLS[id];
  if (!skill) throw new Error(`Unknown skill: ${id}`);
  return {
    ...skill,
    applyStatus: skill.applyStatus.map((s) => ({ ...s })),
    tags: [...skill.tags],
    effects: skill.effects?.map((e) => ({ ...e })),
    softModes: skill.softModes?.map((m) => ({
      ...m,
      when: { ...m.when },
      then: {
        ...m.then,
        effectPatches: m.then.effectPatches?.map((e) => ({ ...e })),
        statusPatches: m.then.statusPatches?.map((s) => ({ ...s })),
        followUp: m.then.followUp ? { ...m.then.followUp } : undefined,
        reviveAlly: m.then.reviveAlly ? { ...m.then.reviveAlly } : undefined,
      },
    })),
  };
}
