import type { UnitTemplate } from '../shared/types.js';

/** 公版卡池：主角 + 10（见 2026-08-01-public-domain-roster-design） */
export const UNIT_TEMPLATES: UnitTemplate[] = [
  {
    id: 'hero',
    name: '主角',
    role: 'flex',
    job: 'adept',
    rarity: 'legendary',
    preferredSlot: 2,
    isHero: true,
    basePhysAtk: 15,
    baseSpiritAtk: 15,
    basePhysDef: 8,
    baseSpiritDef: 8,
    baseMaxHp: 100,
    baseSpd: 12,
    critRating: 18,
    critDmgRating: 10,
    hasteRating: 8,
    versRating: 8,
    masteryRating: 12,
    finalDmgRating: 8,
    fortune: 10,
    maxQi: 100,
    skillId: 'skill_hero_strike',
  },
  {
    id: 'zhangfei',
    name: '张飞',
    role: 'tank',
    job: 'vanguard',
    rarity: 'epic',
    preferredSlot: 1,
    basePhysAtk: 10,
    baseSpiritAtk: 4,
    basePhysDef: 15,
    baseSpiritDef: 10,
    baseMaxHp: 125,
    baseSpd: 9,
    critRating: 8,
    critDmgRating: 8,
    hasteRating: 6,
    versRating: 18,
    masteryRating: 20,
    finalDmgRating: 0,
    fortune: 8,
    maxQi: 100,
    skillId: 'skill_zhangfei_roar',
  },
  {
    id: 'zhaoyun',
    name: '赵云',
    role: 'st_burst',
    job: 'assassin',
    rarity: 'legendary',
    preferredSlot: 9,
    basePhysAtk: 18,
    baseSpiritAtk: 8,
    basePhysDef: 5,
    baseSpiritDef: 4,
    baseMaxHp: 72,
    baseSpd: 15,
    critRating: 28,
    critDmgRating: 22,
    hasteRating: 16,
    versRating: 4,
    masteryRating: 20,
    finalDmgRating: 12,
    fortune: 6,
    maxQi: 100,
    skillId: 'skill_zhaoyun_longdan',
  },
  {
    id: 'wukong',
    name: '孙悟空',
    role: 'aoe_dps',
    job: 'mage',
    rarity: 'legendary',
    preferredSlot: 5,
    basePhysAtk: 14,
    baseSpiritAtk: 12,
    basePhysDef: 6,
    baseSpiritDef: 8,
    baseMaxHp: 88,
    baseSpd: 13,
    critRating: 18,
    critDmgRating: 16,
    hasteRating: 12,
    versRating: 8,
    masteryRating: 14,
    finalDmgRating: 12,
    fortune: 8,
    maxQi: 100,
    skillId: 'skill_wukong_sweep',
  },
  {
    id: 'huatuo',
    name: '华佗',
    role: 'st_heal',
    job: 'healer',
    rarity: 'rare',
    preferredSlot: 8,
    basePhysAtk: 3,
    baseSpiritAtk: 12,
    basePhysDef: 6,
    baseSpiritDef: 11,
    baseMaxHp: 78,
    baseSpd: 10,
    critRating: 5,
    critDmgRating: 5,
    hasteRating: 8,
    versRating: 10,
    masteryRating: 24,
    finalDmgRating: 0,
    fortune: 14,
    maxQi: 100,
    skillId: 'skill_huatuo_qingnang',
  },
  {
    id: 'houyi',
    name: '后羿',
    role: 'st_burst',
    job: 'ranger',
    rarity: 'epic',
    preferredSlot: 7,
    basePhysAtk: 17,
    baseSpiritAtk: 7,
    basePhysDef: 4,
    baseSpiritDef: 4,
    baseMaxHp: 68,
    baseSpd: 14,
    critRating: 26,
    critDmgRating: 24,
    hasteRating: 14,
    versRating: 4,
    masteryRating: 18,
    finalDmgRating: 14,
    fortune: 6,
    maxQi: 100,
    skillId: 'skill_houyi_luori',
    focusPolicy: 'lowest_hp',
  },
  {
    id: 'heracles',
    name: '赫拉克勒斯',
    role: 'tank',
    job: 'vanguard',
    rarity: 'rare',
    preferredSlot: 3,
    basePhysAtk: 9,
    baseSpiritAtk: 4,
    basePhysDef: 16,
    baseSpiritDef: 12,
    baseMaxHp: 135,
    baseSpd: 7,
    critRating: 5,
    critDmgRating: 5,
    hasteRating: 5,
    versRating: 20,
    masteryRating: 22,
    finalDmgRating: 0,
    fortune: 8,
    maxQi: 100,
    skillId: 'skill_heracles_hide',
  },
  {
    id: 'zhuge',
    name: '诸葛亮',
    role: 'group_amp',
    job: 'support',
    rarity: 'legendary',
    preferredSlot: 6,
    basePhysAtk: 5,
    baseSpiritAtk: 14,
    basePhysDef: 6,
    baseSpiritDef: 10,
    baseMaxHp: 80,
    baseSpd: 11,
    critRating: 10,
    critDmgRating: 8,
    hasteRating: 10,
    versRating: 12,
    masteryRating: 26,
    finalDmgRating: 4,
    fortune: 12,
    maxQi: 100,
    skillId: 'skill_zhuge_qimen',
  },
  {
    id: 'baigujing',
    name: '白骨精',
    role: 'aoe_ctrl',
    job: 'warlock',
    rarity: 'epic',
    preferredSlot: 4,
    basePhysAtk: 6,
    baseSpiritAtk: 14,
    basePhysDef: 5,
    baseSpiritDef: 9,
    baseMaxHp: 82,
    baseSpd: 12,
    critRating: 12,
    critDmgRating: 10,
    hasteRating: 10,
    versRating: 8,
    masteryRating: 26,
    finalDmgRating: 4,
    fortune: 10,
    maxQi: 100,
    skillId: 'skill_baigujing_huagu',
  },
  {
    id: 'medusa',
    name: '美杜莎',
    role: 'st_ctrl',
    job: 'warlock',
    rarity: 'epic',
    preferredSlot: 9,
    basePhysAtk: 7,
    baseSpiritAtk: 14,
    basePhysDef: 5,
    baseSpiritDef: 9,
    baseMaxHp: 84,
    baseSpd: 11,
    critRating: 12,
    critDmgRating: 10,
    hasteRating: 10,
    versRating: 8,
    masteryRating: 28,
    finalDmgRating: 4,
    fortune: 12,
    maxQi: 100,
    skillId: 'skill_medusa_gaze',
  },
  {
    id: 'athena',
    name: '雅典娜',
    role: 'aoe_heal',
    job: 'healer',
    rarity: 'epic',
    preferredSlot: 8,
    basePhysAtk: 6,
    baseSpiritAtk: 12,
    basePhysDef: 10,
    baseSpiritDef: 12,
    baseMaxHp: 90,
    baseSpd: 10,
    critRating: 8,
    critDmgRating: 6,
    hasteRating: 8,
    versRating: 16,
    masteryRating: 22,
    finalDmgRating: 2,
    fortune: 10,
    maxQi: 100,
    skillId: 'skill_athena_aegis',
  },
];

export function getTemplate(id: string): UnitTemplate | undefined {
  return UNIT_TEMPLATES.find((t) => t.id === id);
}
