import type { UnitTemplate } from '../shared/types.js';
import { EXPAND_TEMPLATES } from './roster/buildExpand.js';

/**
 * 核心 24（含主角）：24 张均深做技能/星章。
 * 扩展 76：8 张绝品已升格深做，其余职能占位技 + 共用星轨。合计 100。
 */
export const CORE_TEMPLATES: UnitTemplate[] = [
  {
    id: 'hero',
    name: '主角',
    role: 'flex',
    job: 'adept',
    rarity: 'legendary',
    preferredSlot: 2,
    isHero: true,
    damageSchool: 'phys',
    baseAtk: 15,
    baseDef: 8,
    baseRes: 8,
    baseMaxHp: 100,
    baseSpd: 12,
    critRating: 18,
    critDmgRating: 10,
    penRating: 0,
    tenacityRating: 0,
    masteryRating: 12,
    fortuneRating: 10,
    maxQi: 100,
    skillId: 'skill_hero_strike',
  },
  {
    id: 'zhangfei',
    name: '张飞',
    role: 'tank',
    job: 'vanguard',
    rarity: 'legendary',
    preferredSlot: 1,
    damageSchool: 'phys',
    baseAtk: 10,
    baseDef: 15,
    baseRes: 10,
    baseMaxHp: 125,
    baseSpd: 9,
    critRating: 8,
    critDmgRating: 8,
    penRating: 0,
    tenacityRating: 0,
    masteryRating: 20,
    fortuneRating: 8,
    maxQi: 100,
    skillId: 'skill_zhangfei_roar',
  },
  {
    id: 'zhaoyun',
    name: '赵云',
    role: 'st_burst',
    job: 'assassin',
    rarity: 'legendary',
    preferredSlot: 9,
    damageSchool: 'phys',
    baseAtk: 18,
    baseDef: 5,
    baseRes: 4,
    baseMaxHp: 72,
    baseSpd: 15,
    critRating: 28,
    critDmgRating: 22,
    penRating: 0,
    tenacityRating: 0,
    masteryRating: 20,
    fortuneRating: 6,
    maxQi: 100,
    skillId: 'skill_zhaoyun_longdan',
  },
  {
    id: 'wukong',
    name: '孙悟空',
    role: 'aoe_dps',
    job: 'mage',
    rarity: 'legendary',
    preferredSlot: 5,
    damageSchool: 'phys',
    baseAtk: 14,
    baseDef: 6,
    baseRes: 8,
    baseMaxHp: 88,
    baseSpd: 13,
    critRating: 18,
    critDmgRating: 16,
    penRating: 0,
    tenacityRating: 0,
    masteryRating: 14,
    fortuneRating: 8,
    maxQi: 100,
    skillId: 'skill_wukong_sweep',
  },
  {
    id: 'huatuo',
    name: '华佗',
    role: 'st_heal',
    job: 'healer',
    rarity: 'legendary',
    preferredSlot: 8,
    damageSchool: 'spirit',
    baseAtk: 12,
    baseDef: 6,
    baseRes: 11,
    baseMaxHp: 78,
    baseSpd: 10,
    critRating: 5,
    critDmgRating: 5,
    penRating: 0,
    tenacityRating: 0,
    masteryRating: 24,
    fortuneRating: 14,
    maxQi: 100,
    skillId: 'skill_huatuo_qingnang',
  },
  {
    id: 'houyi',
    name: '后羿',
    role: 'st_burst',
    job: 'ranger',
    rarity: 'legendary',
    preferredSlot: 7,
    damageSchool: 'phys',
    baseAtk: 17,
    baseDef: 4,
    baseRes: 4,
    baseMaxHp: 68,
    baseSpd: 14,
    critRating: 26,
    critDmgRating: 24,
    penRating: 0,
    tenacityRating: 0,
    masteryRating: 18,
    fortuneRating: 6,
    maxQi: 100,
    skillId: 'skill_houyi_luori',
    focusPolicy: 'lowest_hp',
  },
  {
    id: 'zhuge',
    name: '诸葛亮',
    role: 'group_amp',
    job: 'support',
    rarity: 'legendary',
    preferredSlot: 6,
    damageSchool: 'spirit',
    baseAtk: 14,
    baseDef: 6,
    baseRes: 10,
    baseMaxHp: 80,
    baseSpd: 11,
    critRating: 10,
    critDmgRating: 8,
    penRating: 0,
    tenacityRating: 0,
    masteryRating: 26,
    fortuneRating: 12,
    maxQi: 100,
    skillId: 'skill_zhuge_qimen',
  },
  {
    id: 'baigujing',
    name: '白骨精',
    role: 'aoe_ctrl',
    job: 'warlock',
    rarity: 'legendary',
    preferredSlot: 4,
    damageSchool: 'spirit',
    baseAtk: 14,
    baseDef: 5,
    baseRes: 9,
    baseMaxHp: 82,
    baseSpd: 12,
    critRating: 12,
    critDmgRating: 10,
    penRating: 0,
    tenacityRating: 0,
    masteryRating: 26,
    fortuneRating: 10,
    maxQi: 100,
    skillId: 'skill_baigujing_huagu',
  },
  {
    id: 'guanyu',
    name: '关羽',
    role: 'st_burst',
    job: 'vanguard',
    rarity: 'legendary',
    preferredSlot: 2,
    damageSchool: 'phys',
    baseAtk: 17,
    baseDef: 10,
    baseRes: 7,
    baseMaxHp: 105,
    baseSpd: 11,
    critRating: 16,
    critDmgRating: 14,
    penRating: 0,
    tenacityRating: 0,
    masteryRating: 14,
    fortuneRating: 8,
    maxQi: 100,
    skillId: 'skill_guanyu_slash',
  },
  {
    id: 'lvbu',
    name: '吕布',
    role: 'st_burst',
    job: 'assassin',
    rarity: 'legendary',
    preferredSlot: 9,
    damageSchool: 'phys',
    baseAtk: 20,
    baseDef: 5,
    baseRes: 4,
    baseMaxHp: 78,
    baseSpd: 14,
    critRating: 30,
    critDmgRating: 24,
    penRating: 0,
    tenacityRating: 0,
    masteryRating: 16,
    fortuneRating: 5,
    maxQi: 100,
    skillId: 'skill_lvbu_wushuang',
  },
  {
    id: 'dianwei',
    name: '典韦',
    role: 'tank',
    job: 'vanguard',
    rarity: 'legendary',
    preferredSlot: 1,
    damageSchool: 'phys',
    baseAtk: 11,
    baseDef: 17,
    baseRes: 11,
    baseMaxHp: 140,
    baseSpd: 7,
    critRating: 6,
    critDmgRating: 6,
    penRating: 0,
    tenacityRating: 0,
    masteryRating: 20,
    fortuneRating: 7,
    maxQi: 100,
    skillId: 'skill_dianwei_guard',
  },
  {
    id: 'nezha',
    name: '哪吒',
    role: 'flex',
    job: 'adept',
    rarity: 'legendary',
    preferredSlot: 5,
    damageSchool: 'phys',
    baseAtk: 15,
    baseDef: 7,
    baseRes: 7,
    baseMaxHp: 90,
    baseSpd: 15,
    critRating: 20,
    critDmgRating: 16,
    penRating: 0,
    tenacityRating: 0,
    masteryRating: 14,
    fortuneRating: 9,
    maxQi: 100,
    skillId: 'skill_nezha_arms',
  },
  {
    id: 'daji',
    name: '妲己',
    role: 'aoe_ctrl',
    job: 'warlock',
    rarity: 'legendary',
    preferredSlot: 4,
    damageSchool: 'spirit',
    baseAtk: 15,
    baseDef: 5,
    baseRes: 9,
    baseMaxHp: 80,
    baseSpd: 12,
    critRating: 12,
    critDmgRating: 10,
    penRating: 0,
    tenacityRating: 0,
    masteryRating: 28,
    fortuneRating: 11,
    maxQi: 100,
    skillId: 'skill_daji_charm',
  },
  {
    id: 'yangjian',
    name: '杨戬',
    role: 'st_burst',
    job: 'ranger',
    rarity: 'legendary',
    preferredSlot: 7,
    damageSchool: 'phys',
    baseAtk: 17,
    baseDef: 6,
    baseRes: 6,
    baseMaxHp: 86,
    baseSpd: 14,
    critRating: 24,
    critDmgRating: 20,
    penRating: 0,
    tenacityRating: 0,
    masteryRating: 18,
    fortuneRating: 8,
    maxQi: 100,
    skillId: 'skill_yangjian_blade',
    focusPolicy: 'lowest_hp',
  },
  {
    id: 'change',
    name: '嫦娥',
    role: 'aoe_heal',
    job: 'healer',
    rarity: 'legendary',
    preferredSlot: 8,
    damageSchool: 'spirit',
    baseAtk: 14,
    baseDef: 6,
    baseRes: 12,
    baseMaxHp: 88,
    baseSpd: 11,
    critRating: 6,
    critDmgRating: 6,
    penRating: 0,
    tenacityRating: 0,
    masteryRating: 24,
    fortuneRating: 12,
    maxQi: 100,
    skillId: 'skill_change_moon',
  },
  {
    id: 'xishi',
    name: '西施',
    role: 'st_ctrl',
    job: 'warlock',
    rarity: 'legendary',
    preferredSlot: 6,
    damageSchool: 'spirit',
    baseAtk: 15,
    baseDef: 5,
    baseRes: 10,
    baseMaxHp: 82,
    baseSpd: 12,
    critRating: 10,
    critDmgRating: 8,
    penRating: 0,
    tenacityRating: 0,
    masteryRating: 28,
    fortuneRating: 12,
    maxQi: 100,
    skillId: 'skill_xishi_chenyu',
  },
  {
    id: 'sunbin',
    name: '孙膑',
    role: 'group_amp',
    job: 'support',
    rarity: 'legendary',
    preferredSlot: 6,
    damageSchool: 'spirit',
    baseAtk: 15,
    baseDef: 6,
    baseRes: 11,
    baseMaxHp: 84,
    baseSpd: 11,
    critRating: 10,
    critDmgRating: 8,
    penRating: 0,
    tenacityRating: 0,
    masteryRating: 28,
    fortuneRating: 11,
    maxQi: 100,
    skillId: 'skill_sunbin_jianzao',
  },
];

/** 中土深做：手填核心 + 扩展升格（国外已下架）。 */
export const DEEP_TEMPLATE_IDS = [
  'hero',
  'zhaoyun',
  'guanyu',
  'zhangfei',
  'lvbu',
  'dianwei',
  'wukong',
  'nezha',
  'yangjian',
  'huatuo',
  'zhuge',
  'baigujing',
  'daji',
  'houyi',
  'xishi',
  'change',
  'sunbin',
  'zhouyu',
  'xiangyu',
  'nuwa',
  'yuefei',
  'jiangziya',
  'liubei',
  'pangtong',
  'niumowang',
  'tangseng',
  'tieshan',
] as const;

/** 已空：核心暂缓 4 张于 2026-08-26 升格。保留导出以免旧测试/索引断掉。 */
export const STUB_CORE_IDS = [] as const;

export const UNIT_TEMPLATES: UnitTemplate[] = [...CORE_TEMPLATES, ...EXPAND_TEMPLATES];

export function getTemplate(id: string): UnitTemplate | undefined {
  return UNIT_TEMPLATES.find((t) => t.id === id);
}
