import type { Rarity, Role } from '../../shared/types.js';

export type UnlockBatch = 'start' | 'ch1' | 'ch2' | 'ch3' | 'ch4' | 'ch5' | 'ch6';

export interface ExpandEntry {
  id: string; name: string; lore: string; motif: string;
  role: Role; rarity: Rarity; skillName: string; unlock: UnlockBatch;
}

/** 扩展 76 卡（占位技+共用星轨）。稀有度：绝稀 / 珍中 / 良凡为主护抽卡。 */
export const EXPAND_ROSTER: ExpandEntry[] = [
  { id: 'caocao', name: '曹操', lore: '三国', motif: '乱世奸雄', role: 'group_amp', rarity: 'epic', skillName: '权谋', unlock: 'ch2' },
  { id: 'liubei', name: '刘备', lore: '三国', motif: '仁德聚义', role: 'aoe_heal', rarity: 'epic', skillName: '桃园', unlock: 'start' },
  { id: 'sunquan', name: '孙权', lore: '三国', motif: '坐断东南', role: 'flex', rarity: 'rare', skillName: '虎踞', unlock: 'ch2' },
  { id: 'zhouyu', name: '周瑜', lore: '三国', motif: '火烧赤壁', role: 'aoe_dps', rarity: 'legendary', skillName: '赤壁', unlock: 'ch5' },
  { id: 'simayi', name: '司马懿', lore: '三国', motif: '隐忍鹰视', role: 'group_amp', rarity: 'legendary', skillName: '鹰视', unlock: 'ch6' },
  { id: 'machao', name: '马超', lore: '三国', motif: '锦马超突击', role: 'st_burst', rarity: 'epic', skillName: '西凉', unlock: 'ch3' },
  { id: 'huangzhong', name: '黄忠', lore: '三国', motif: '百步穿杨老将', role: 'st_burst', rarity: 'rare', skillName: '定军', unlock: 'ch1' },
  { id: 'xiaoqiao', name: '小乔', lore: '三国', motif: '铜雀春深', role: 'st_ctrl', rarity: 'common', skillName: '挽歌', unlock: 'ch2' },
  { id: 'diaochan', name: '貂蝉', lore: '三国', motif: '连环计乱心', role: 'aoe_ctrl', rarity: 'epic', skillName: '连环', unlock: 'ch4' },
  { id: 'xuchu', name: '许褚', lore: '三国', motif: '虎痴护主', role: 'tank', rarity: 'epic', skillName: '虎痴', unlock: 'start' },
  { id: 'ganning', name: '甘宁', lore: '三国', motif: '锦帆劫营', role: 'st_burst', rarity: 'common', skillName: '锦帆', unlock: 'ch1' },
  { id: 'taishici', name: '太史慈', lore: '三国', motif: '神亭酣斗', role: 'flex', rarity: 'rare', skillName: '神亭', unlock: 'ch2' },
  { id: 'pangtong', name: '庞统', lore: '三国', motif: '凤雏奇策', role: 'group_amp', rarity: 'epic', skillName: '落凤', unlock: 'ch4' },
  { id: 'jiangwei', name: '姜维', lore: '三国', motif: '九伐中原', role: 'st_burst', rarity: 'rare', skillName: '北伐', unlock: 'ch5' },
  { id: 'zhangliao', name: '张辽', lore: '三国', motif: '威震逍遥津', role: 'aoe_dps', rarity: 'epic', skillName: '逍遥', unlock: 'ch3' },
  { id: 'xuhuang', name: '徐晃', lore: '三国', motif: '断粮围城', role: 'tank', rarity: 'common', skillName: '围城', unlock: 'ch1' },
  { id: 'menghuo', name: '孟获', lore: '三国', motif: '七擒不屈', role: 'tank', rarity: 'common', skillName: '南蛮', unlock: 'start' },
  { id: 'zhurong', name: '祝融', lore: '三国', motif: '飞刀火神', role: 'aoe_dps', rarity: 'rare', skillName: '火神', unlock: 'ch1' },
  { id: 'caiwenji', name: '蔡文姬', lore: '三国', motif: '胡笳悲歌', role: 'aoe_heal', rarity: 'rare', skillName: '胡笳', unlock: 'ch4' },
  { id: 'bajie', name: '猪八戒', lore: '西游', motif: '天蓬巡海', role: 'tank', rarity: 'rare', skillName: '钉耙', unlock: 'start' },
  { id: 'shaseng', name: '沙僧', lore: '西游', motif: '流沙护法', role: 'tank', rarity: 'common', skillName: '降妖', unlock: 'start' },
  { id: 'tangseng', name: '唐僧', lore: '西游', motif: '紧箍度厄', role: 'st_heal', rarity: 'epic', skillName: '紧箍', unlock: 'ch4' },
  { id: 'lijing', name: '李靖', lore: '封神', motif: '托塔镇天', role: 'group_amp', rarity: 'rare', skillName: '宝塔', unlock: 'ch5' },
  { id: 'leizhenzi', name: '雷震子', lore: '封神', motif: '风雷双翅', role: 'aoe_dps', rarity: 'common', skillName: '风雷', unlock: 'ch2' },
  { id: 'jiangziya', name: '姜子牙', lore: '封神', motif: '封神榜主', role: 'group_amp', rarity: 'legendary', skillName: '封神', unlock: 'ch6' },
  { id: 'nuwa', name: '女娲', lore: '神话', motif: '补天造人', role: 'aoe_heal', rarity: 'legendary', skillName: '补天', unlock: 'ch6' },
  { id: 'fuxi', name: '伏羲', lore: '神话', motif: '八卦推演', role: 'group_amp', rarity: 'epic', skillName: '八卦', unlock: 'ch5' },
  { id: 'kuafu', name: '夸父', lore: '神话', motif: '逐日不悔', role: 'flex', rarity: 'common', skillName: '逐日', unlock: 'ch1' },
  { id: 'jingwei', name: '精卫', lore: '神话', motif: '填海不息', role: 'st_burst', rarity: 'rare', skillName: '填海', unlock: 'ch2' },
  { id: 'xingtian', name: '刑天', lore: '神话', motif: '干戚起舞', role: 'tank', rarity: 'epic', skillName: '干戚', unlock: 'ch4' },
  { id: 'chiyou', name: '蚩尤', lore: '神话', motif: '兵主开战', role: 'aoe_dps', rarity: 'legendary', skillName: '兵主', unlock: 'ch6' },
  { id: 'shennong', name: '神农', lore: '神话', motif: '尝百草济世', role: 'st_heal', rarity: 'epic', skillName: '百草', unlock: 'ch4' },
  { id: 'dayu', name: '大禹', lore: '神话', motif: '治水定川', role: 'flex', rarity: 'epic', skillName: '定川', unlock: 'ch5' },
  { id: 'gonggong', name: '共工', lore: '神话', motif: '怒触不周', role: 'aoe_ctrl', rarity: 'common', skillName: '洪水', unlock: 'ch2' },
  { id: 'nuba', name: '旱魃', lore: '神话', motif: '赤地千里', role: 'aoe_ctrl', rarity: 'rare', skillName: '焦土', unlock: 'ch5' },
  { id: 'zeus', name: '宙斯', lore: '希腊', motif: '雷霆王座', role: 'aoe_dps', rarity: 'legendary', skillName: '雷霆', unlock: 'ch6' },
  { id: 'poseidon', name: '波塞冬', lore: '希腊', motif: '海啸倾覆', role: 'aoe_ctrl', rarity: 'epic', skillName: '海啸', unlock: 'ch5' },
  { id: 'hades', name: '哈迪斯', lore: '希腊', motif: '冥界收魂', role: 'st_ctrl', rarity: 'legendary', skillName: '冥界', unlock: 'ch6' },
  { id: 'apollo', name: '阿波罗', lore: '希腊', motif: '日轮箭', role: 'st_burst', rarity: 'epic', skillName: '日轮', unlock: 'ch4' },
  { id: 'artemis', name: '阿尔忒弥斯', lore: '希腊', motif: '月狩穿林', role: 'st_burst', rarity: 'rare', skillName: '月狩', unlock: 'ch4' },
  { id: 'ares', name: '阿瑞斯', lore: '希腊', motif: '战狂冲阵', role: 'flex', rarity: 'rare', skillName: '战狂', unlock: 'ch2' },
  { id: 'hermes', name: '赫尔墨斯', lore: '希腊', motif: '神使疾行', role: 'flex', rarity: 'common', skillName: '疾行', unlock: 'ch1' },
  { id: 'hephaestus', name: '赫菲斯托斯', lore: '希腊', motif: '锻火铸盾', role: 'tank', rarity: 'common', skillName: '锻火', unlock: 'ch3' },
  { id: 'aphrodite', name: '阿佛洛狄忒', lore: '希腊', motif: '爱欲乱心', role: 'aoe_ctrl', rarity: 'epic', skillName: '金苹果', unlock: 'ch4' },
  { id: 'perseus', name: '珀尔修斯', lore: '希腊', motif: '斩蛇取首', role: 'st_burst', rarity: 'common', skillName: '蛇首', unlock: 'ch2' },
  { id: 'odysseus', name: '奥德修斯', lore: '希腊', motif: '木马奇计', role: 'group_amp', rarity: 'epic', skillName: '木马', unlock: 'ch5' },
  { id: 'achilles', name: '阿喀琉斯', lore: '希腊', motif: '踵伤不灭', role: 'st_burst', rarity: 'legendary', skillName: '阿喀琉斯', unlock: 'ch5' },
  { id: 'hector', name: '赫克托耳', lore: '希腊', motif: '城墙之盾', role: 'tank', rarity: 'epic', skillName: '城墙', unlock: 'ch4' },
  { id: 'orpheus', name: '俄耳甫斯', lore: '希腊', motif: '琴声引灵', role: 'aoe_heal', rarity: 'common', skillName: '琴声', unlock: 'ch3' },
  { id: 'circe', name: '喀耳刻', lore: '希腊', motif: '药酒变形', role: 'st_ctrl', rarity: 'rare', skillName: '药酒', unlock: 'ch4' },
  { id: 'prometheus', name: '普罗米修斯', lore: '希腊', motif: '盗火予人', role: 'group_amp', rarity: 'epic', skillName: '盗火', unlock: 'ch5' },
  { id: 'atlas', name: '阿特拉斯', lore: '希腊', motif: '负天承压', role: 'tank', rarity: 'common', skillName: '负天', unlock: 'ch1' },
  { id: 'hera', name: '赫拉', lore: '希腊', motif: '妒火惩戒', role: 'st_ctrl', rarity: 'rare', skillName: '妒火', unlock: 'ch4' },
  { id: 'dionysus', name: '狄俄尼索斯', lore: '希腊', motif: '狂欢迷醉', role: 'aoe_ctrl', rarity: 'common', skillName: '狂欢', unlock: 'ch3' },
  { id: 'odin', name: '奥丁', lore: '北欧', motif: '独眼求知', role: 'group_amp', rarity: 'legendary', skillName: '卢恩', unlock: 'ch6' },
  { id: 'loki', name: '洛基', lore: '北欧', motif: '狡计易形', role: 'aoe_ctrl', rarity: 'epic', skillName: '狡计', unlock: 'ch4' },
  { id: 'freya', name: '芙蕾雅', lore: '北欧', motif: '爱战双面', role: 'flex', rarity: 'epic', skillName: '猫车', unlock: 'ch4' },
  { id: 'tyr', name: '提尔', lore: '北欧', motif: '断腕守誓', role: 'tank', rarity: 'rare', skillName: '断腕', unlock: 'ch3' },
  { id: 'heimdall', name: '海姆达尔', lore: '北欧', motif: '虹桥警视', role: 'st_ctrl', rarity: 'common', skillName: '虹桥', unlock: 'ch3' },
  { id: 'baldur', name: '巴德尔', lore: '北欧', motif: '无瑕光辉', role: 'aoe_heal', rarity: 'rare', skillName: '光辉', unlock: 'ch1' },
  { id: 'skadi', name: '丝卡蒂', lore: '北欧', motif: '冬猎追击', role: 'st_burst', rarity: 'common', skillName: '冬猎', unlock: 'ch3' },
  { id: 'fenrir', name: '芬里尔', lore: '北欧', motif: '缚链疯狼', role: 'st_burst', rarity: 'epic', skillName: '疯狼', unlock: 'ch5' },
  { id: 'lancelot', name: '兰斯洛特', lore: '亚瑟', motif: '湖畔第一骑士', role: 'st_burst', rarity: 'legendary', skillName: '湖畔', unlock: 'ch5' },
  { id: 'gawain', name: '高文', lore: '亚瑟', motif: '午时烈阳', role: 'aoe_dps', rarity: 'epic', skillName: '烈阳', unlock: 'ch4' },
  { id: 'merlin', name: '梅林', lore: '亚瑟', motif: '预言法师', role: 'group_amp', rarity: 'legendary', skillName: '预言', unlock: 'ch6' },
  { id: 'morgana', name: '摩根勒菲', lore: '亚瑟', motif: '雾岛诅咒', role: 'aoe_ctrl', rarity: 'epic', skillName: '雾岛', unlock: 'ch5' },
  { id: 'guinevere', name: '桂妮薇儿', lore: '亚瑟', motif: '圆桌王后', role: 'aoe_heal', rarity: 'common', skillName: '圆桌', unlock: 'ch3' },
  { id: 'mordred', name: '莫德雷德', lore: '亚瑟', motif: '叛誓逆刺', role: 'st_burst', rarity: 'rare', skillName: '叛誓', unlock: 'ch5' },
  { id: 'mulan', name: '花木兰', lore: '中国', motif: '替父从军', role: 'flex', rarity: 'epic', skillName: '木兰', unlock: 'ch3' },
  { id: 'yuefei', name: '岳飞', lore: '中国', motif: '精忠报国', role: 'st_burst', rarity: 'legendary', skillName: '精忠', unlock: 'ch6' },
  { id: 'xiangyu', name: '项羽', lore: '中国', motif: '破釜沉舟', role: 'aoe_dps', rarity: 'legendary', skillName: '霸王', unlock: 'ch5' },
  { id: 'hanxin', name: '韩信', lore: '中国', motif: '背水奇阵', role: 'group_amp', rarity: 'epic', skillName: '背水', unlock: 'ch4' },
  { id: 'jingke', name: '荆轲', lore: '中国', motif: '图穷匕见', role: 'st_burst', rarity: 'epic', skillName: '匕见', unlock: 'ch4' },
  { id: 'quyuan', name: '屈原', lore: '中国', motif: '离骚问天', role: 'st_heal', rarity: 'common', skillName: '离骚', unlock: 'ch3' },
  { id: 'libai', name: '李白', lore: '中国', motif: '斗酒诗百篇', role: 'aoe_dps', rarity: 'rare', skillName: '青莲', unlock: 'ch4' },
  { id: 'mozi', name: '墨子', lore: '中国', motif: '兼爱非攻', role: 'tank', rarity: 'rare', skillName: '非攻', unlock: 'ch2' },
];

export function expandIdsByUnlock(batch: UnlockBatch): string[] {
  return EXPAND_ROSTER.filter((e) => e.unlock === batch).map((e) => e.id);
}
