/** 中土故事圈全表（含主角）。由 spec 表生成，勿手改人数。 */
import type { Rarity, Role } from '../../shared/types.js';
import {
  CIRCLE_LABELS,
  unlockFor,
  type CircleId,
  type UnlockBatch,
} from './circles.js';
import type { KitId } from './kitCompose.js';

export interface ZhongtuEntry {
  id: string;
  name: string;
  circleId: CircleId | null;
  rarity: Rarity;
  role: Role;
  motif: string;
  skillName: string;
  lore: string;
  unlock: UnlockBatch | null;
  kits: KitId[];
}

const ROWS: Array<[
  string, string, CircleId | null, Rarity, Role, string, string, KitId, KitId, KitId
]> = [
  ['liubei', '刘备', 'shu', 'legendary', 'aoe_heal', '仁德聚义', '桃园结义', 'team_heal', 'slow_pin', 'flex_qi'],
  ['guanyu', '关羽', 'shu', 'legendary', 'st_burst', '温酒斩将', '温酒青龙', 'bleed_pierce', 'slow_pin', 'flex_qi'],
  ['zhangfei', '张飞', 'shu', 'legendary', 'tank', '当阳桥头一声喝', '当阳吼', 'guard', 'slow_pin', 'flex_qi'],
  ['zhaoyun', '赵云', 'shu', 'legendary', 'st_burst', '长坂坡七进七出', '龙胆枪', 'execute', 'surround_aoe', 'heal_low'],
  ['zhuge', '诸葛亮', 'shu', 'legendary', 'group_amp', '借东风布八阵', '借东风', 'qi_drought', 'amp_qi', 'slow_pin'],
  ['pangtong', '庞统', 'shu', 'legendary', 'group_amp', '落凤坡连环营', '落凤坡', 'amp_atk', 'slow_pin', 'flex_qi'],
  ['huatuo', '华佗', 'shu', 'legendary', 'st_heal', '剖骨疗毒', '青囊济世', 'heal_cleanse', 'slow_pin', 'flex_qi'],
  ['machao', '马超', 'shu', 'epic', 'st_burst', '西凉铁骑', '马诀', 'hunt_back', 'flex_bleed', 'first_strike'],
  ['huangyueying', '黄月英', 'shu', 'epic', 'group_amp', '木牛流马', '黄诀', 'amp_qi', 'surround_aoe', 'heal_low'],
  ['huangzhong', '黄忠', 'shu', 'epic', 'st_burst', '百步穿杨', '黄忠·黄诀', 'high_hp', 'flex_qi', 'col_kill'],
  ['jiangwei', '姜维', 'shu', 'epic', 'st_burst', '九伐中原', '姜诀', 'first_strike', 'heal_low', 'amp_def'],
  ['xushu', '徐庶', 'shu', 'rare', 'group_amp', '走马荐诸葛', '徐诀', 'amp_spd', 'flex_bleed', 'first_strike'],
  ['weiyan', '魏延', 'shu', 'rare', 'flex', '子午奇谋', '魏诀', 'flex_purge', 'slow_pin', 'flex_qi'],
  ['zhurong', '祝融', 'shu', 'rare', 'aoe_dps', '火神祝融', '祝诀', 'row_smash', 'slow_pin', 'flex_qi'],
  ['menghuo', '孟获', 'shu', 'common', 'tank', '南中喝阵', '孟诀', 'taunt', 'surround_aoe', 'heal_low'],
  ['caocao', '曹操', 'qunxiong', 'legendary', 'group_amp', '挟天子令', '挟天子', 'qi_drought', 'flex_qi', 'high_hp'],
  ['lvbu', '吕布', 'qunxiong', 'legendary', 'st_burst', '辕门射戟', '方天画戟', 'col_kill', 'first_strike', 'slow_pin'],
  ['zhouyu', '周瑜', 'qunxiong', 'legendary', 'aoe_dps', '火烧赤壁', '赤壁业火', 'cross_hit', 'surround_aoe', 'heal_low'],
  ['simayi', '司马懿', 'qunxiong', 'legendary', 'group_amp', '冢虎隐忍', '鹰视狼顾', 'amp_def', 'heal_low', 'amp_qi'],
  ['dianwei', '典韦', 'qunxiong', 'legendary', 'tank', '死守营门', '恶来守营', 'earth', 'flex_bleed', 'first_strike'],
  ['guojia', '郭嘉', 'qunxiong', 'legendary', 'group_amp', '十胜十败', '郭诀', 'amp_atk', 'first_strike', 'slow_pin'],
  ['xuchu', '许褚', 'qunxiong', 'epic', 'tank', '虎痴挡关', '许诀', 'first_guard', 'flex_qi', 'high_hp'],
  ['zhangliao', '张辽', 'qunxiong', 'epic', 'aoe_dps', '威震逍遥', '张诀', 'col_wave', 'flex_bleed', 'first_strike'],
  ['diaochan', '貂蝉', 'qunxiong', 'epic', 'aoe_ctrl', '闭月乱心', '貂诀', 'havoc', 'slow_pin', 'flex_qi'],
  ['luxun', '陆逊', 'qunxiong', 'epic', 'aoe_dps', '火烧连营', '陆诀', 'surround_aoe', 'flex_qi', 'high_hp'],
  ['chengong', '陈宫', 'qunxiong', 'rare', 'st_ctrl', '弃曹归吕', '陈诀', 'stun', 'slow_pin', 'flex_qi'],
  ['sunquan', '孙权', 'qunxiong', 'epic', 'flex', '坐断东南', '孙诀', 'flex_first', 'surround_aoe', 'heal_low'],
  ['taishici', '太史慈', 'qunxiong', 'rare', 'flex', '神亭酣斗', '太诀', 'flex_bleed', 'flex_qi', 'first_strike'],
  ['daqiao', '大乔', 'qunxiong', 'epic', 'aoe_heal', '二乔锁江', '大诀', 'team_aegis', 'surround_aoe', 'heal_low'],
  ['caiwenji', '蔡文姬', 'qunxiong', 'rare', 'aoe_heal', '胡笳十八', '蔡诀', 'heal_low', 'flex_bleed', 'first_strike'],
  ['xiaoqiao', '小乔', 'qunxiong', 'common', 'st_ctrl', '以曲封喉', '小诀', 'silence', 'surround_aoe', 'heal_low'],
  ['ganning', '甘宁', 'qunxiong', 'common', 'st_burst', '锦帆劫营', '甘诀', 'mark_hunt', 'high_hp', 'surround_aoe'],
  ['wukong', '孙悟空', 'xiyou', 'legendary', 'aoe_dps', '金箍棒扫开天地', '定海神针', 'first_wave', 'heal_low', 'amp_def'],
  ['baigujing', '白骨精', 'xiyou', 'legendary', 'aoe_ctrl', '化骨惑心', '化骨绵掌', 'mass_slow', 'surround_aoe', 'heal_low'],
  ['niumowang', '牛魔王', 'xiyou', 'legendary', 'tank', '混世魔王', '混世魔王', 'team_wall', 'heal_low', 'amp_def'],
  ['tangseng', '唐僧', 'xiyou', 'legendary', 'st_heal', '金蝉西行', '紧箍咒', 'heal_low', 'surround_aoe', 'heal_cleanse'],
  ['tieshan', '铁扇公主', 'xiyou', 'legendary', 'aoe_ctrl', '芭蕉扇灭火', '芭蕉扇', 'mass_silence', 'flex_bleed', 'first_strike'],
  ['honghaier', '红孩儿', 'xiyou', 'epic', 'aoe_dps', '三昧真火', '红诀', 'row_smash', 'first_strike', 'slow_pin'],
  ['zhenyuanzi', '镇元子', 'xiyou', 'epic', 'group_amp', '人参果园', '镇诀', 'amp_qi', 'high_hp', 'surround_aoe'],
  ['bajie', '猪八戒', 'xiyou', 'epic', 'tank', '高老庄变', '猪诀', 'hp_guard', 'first_strike', 'slow_pin'],
  ['bailongma', '白龙马', 'xiyou', 'rare', 'flex', '西海龙驹', '白诀', 'flex_stun', 'flex_qi', 'high_hp'],
  ['jinjiao', '金角', 'xiyou', 'rare', 'st_burst', '紫金葫芦', '金诀', 'bleed_pierce', 'amp_def', 'flex_bleed'],
  ['yinjiao', '银角', 'xiyou', 'rare', 'st_burst', '羊脂玉净', '银诀', 'execute', 'slow_pin', 'flex_qi'],
  ['nvguowang', '女儿国王', 'xiyou', 'rare', 'st_ctrl', '招赘西行', '女诀', 'heal_block', 'flex_bleed', 'first_strike'],
  ['zhizhujing', '蜘蛛精', 'xiyou', 'rare', 'aoe_ctrl', '盘丝困神', '蜘诀', 'mass_sleep', 'flex_qi', 'high_hp'],
  ['shaseng', '沙僧', 'xiyou', 'common', 'tank', '流沙护法', '沙诀', 'guard', 'high_hp', 'surround_aoe'],
  ['taibai', '太白金星', 'xiyou', 'common', 'group_amp', '金星说项', '太白金星·太诀', 'amp_spd', 'amp_def', 'flex_bleed'],
  ['huangfeng', '黄风怪', 'xiyou', 'common', 'aoe_ctrl', '黄风迷眼', '黄风怪·黄诀', 'slow_pin', 'heal_low', 'amp_def'],
  ['nezha', '哪吒', 'fengshen', 'legendary', 'flex', '风火闹海', '风火轮', 'flex_qi', 'heal_low', 'amp_def'],
  ['yangjian', '杨戬', 'fengshen', 'legendary', 'st_burst', '天眼照妖', '三尖两刃', 'hunt_back', 'surround_aoe', 'heal_low'],
  ['jiangziya', '姜子牙', 'fengshen', 'legendary', 'group_amp', '榜上有名', '封神榜', 'qi_drought', 'slow_pin', 'flex_qi'],
  ['daji', '妲己', 'fengshen', 'legendary', 'aoe_ctrl', '九尾惑纣', '狐媚惑心', 'havoc', 'first_strike', 'slow_pin'],
  ['shengongbao', '申公豹', 'fengshen', 'legendary', 'st_ctrl', '妨贤害能', '申诀', 'sleep', 'flex_qi', 'high_hp'],
  ['aobing', '敖丙', 'fengshen', 'legendary', 'aoe_dps', '龙太子浪', '敖诀', 'cross_hit', 'high_hp', 'surround_aoe'],
  ['taiyi', '太乙真人', 'fengshen', 'legendary', 'aoe_heal', '莲花化身', '太乙真人·太诀', 'heal_cleanse', 'flex_qi', 'high_hp'],
  ['wenzhong', '闻仲', 'fengshen', 'epic', 'aoe_dps', '金鞭开路', '闻诀', 'col_wave', 'amp_def', 'flex_bleed'],
  ['zhaogongming', '赵公明', 'fengshen', 'epic', 'st_ctrl', '财神锁脉', '赵诀', 'slow_pin', 'heal_low', 'amp_def'],
  ['zhouwang', '纣王', 'fengshen', 'epic', 'flex', '酒池肉林', '纣诀', 'first_strike', 'high_hp', 'slow_pin'],
  ['lijing', '李靖', 'fengshen', 'epic', 'group_amp', '托塔镇宅', '李诀', 'amp_def', 'surround_aoe', 'heal_low'],
  ['yunxiao', '云霄', 'fengshen', 'epic', 'aoe_ctrl', '金蛟剪水', '云诀', 'mass_slow', 'high_hp', 'surround_aoe'],
  ['huangfeihu', '黄飞虎', 'fengshen', 'rare', 'tank', '反商归周', '黄飞虎·黄诀', 'taunt', 'amp_def', 'flex_bleed'],
  ['tuxingsun', '土行孙', 'fengshen', 'rare', 'st_burst', '土遁奇袭', '土诀', 'high_hp', 'flex_bleed', 'first_strike'],
  ['dengchanyu', '邓婵玉', 'fengshen', 'rare', 'st_burst', '五光石打', '邓诀', 'first_strike', 'flex_qi', 'high_hp'],
  ['leizhenzi', '雷震子', 'fengshen', 'common', 'aoe_dps', '风雷展翅', '风雷翅', 'surround_aoe', 'slow_pin', 'flex_qi'],
  ['qiongxiao', '琼霄', 'fengshen', 'common', 'aoe_ctrl', '混元金斗', '琼诀', 'mass_silence', 'amp_def', 'flex_bleed'],
  ['bixiao', '碧霄', 'fengshen', 'common', 'aoe_ctrl', '金蛟困神', '碧诀', 'mass_sleep', 'slow_pin', 'flex_qi'],
  ['nuwa', '女娲', 'shanggu', 'legendary', 'aoe_heal', '炼石补天', '补天炼石', 'team_heal', 'heal_low', 'amp_def'],
  ['huangdi', '黄帝', 'shanggu', 'legendary', 'group_amp', '涿鹿誓师', '涿鹿誓师', 'amp_atk', 'flex_bleed', 'first_strike'],
  ['chiyou', '蚩尤', 'shanggu', 'legendary', 'aoe_dps', '兵主开战', '兵主开战', 'first_wave', 'surround_aoe', 'heal_low'],
  ['houyi', '后羿', 'shanggu', 'legendary', 'st_burst', '射落九日', '九日尽', 'col_kill', 'heal_low', 'amp_def'],
  ['xiwangmu', '西王母', 'shanggu', 'legendary', 'st_ctrl', '瑶池点穴', '瑶池点穴', 'stun', 'first_strike', 'slow_pin'],
  ['change', '嫦娥', 'shanggu', 'legendary', 'aoe_heal', '奔月余晖', '月华清辉', 'team_aegis', 'first_strike', 'slow_pin'],
  ['fuxi', '伏羲', 'shanggu', 'legendary', 'group_amp', '一画开天', '一画开天', 'amp_qi', 'flex_qi', 'high_hp'],
  ['dayu', '大禹', 'shanggu', 'legendary', 'flex', '疏河定州', '疏河定州', 'flex_purge', 'high_hp', 'surround_aoe'],
  ['shennong', '神农', 'shanggu', 'epic', 'st_heal', '百草试毒', '神诀', 'regen', 'flex_bleed', 'first_strike'],
  ['xingtian', '刑天', 'shanggu', 'epic', 'tank', '干戚再战', '干戚舞', 'earth', 'slow_pin', 'flex_qi'],
  ['jingwei', '精卫', 'shanggu', 'epic', 'st_burst', '衔石填海', '精诀', 'mark_hunt', 'first_strike', 'slow_pin'],
  ['nuba', '旱魃', 'shanggu', 'rare', 'aoe_ctrl', '赤地千里', '旱诀', 'slow_pin', 'surround_aoe', 'heal_low'],
  ['zhurongshi', '祝融氏', 'shanggu', 'rare', 'aoe_dps', '祝融焚营', '祝融氏·祝诀', 'row_smash', 'flex_bleed', 'first_strike'],
  ['kuafu', '夸父', 'shanggu', 'common', 'flex', '逐日不歇', '夸诀', 'flex_first', 'amp_def', 'flex_bleed'],
  ['gonggong', '共工', 'shanggu', 'common', 'aoe_ctrl', '怒触不周', '共诀', 'havoc', 'flex_bleed', 'first_strike'],
  ['jumang', '句芒', 'shanggu', 'common', 'flex', '春神带刃', '句诀', 'flex_bleed', 'slow_pin', 'flex_qi'],
  ['lvdongbin', '吕洞宾', 'baxian', 'legendary', 'st_burst', '剑仙斩妖', '吕诀', 'bleed_pierce', 'high_hp', 'surround_aoe'],
  ['hanzhongli', '汉钟离', 'baxian', 'legendary', 'tank', '轻摇宝扇', '汉诀', 'first_guard', 'surround_aoe', 'heal_low'],
  ['tieguaili', '铁拐李', 'baxian', 'legendary', 'st_heal', '铁拐济世', '铁诀', 'heal_cleanse', 'flex_qi', 'high_hp'],
  ['aoguang', '敖广', 'baxian', 'legendary', 'aoe_ctrl', '龙王掀浪', '敖广·敖诀', 'mass_slow', 'flex_qi', 'high_hp'],
  ['hexiangu', '何仙姑', 'baxian', 'epic', 'aoe_heal', '荷花济人', '何诀', 'heal_low', 'high_hp', 'surround_aoe'],
  ['zhangguolao', '张果老', 'baxian', 'epic', 'flex', '倒骑神驴', '张果老·张诀', 'flex_stun', 'surround_aoe', 'heal_low'],
  ['hanxiangzi', '韩湘子', 'baxian', 'rare', 'aoe_dps', '紫箫裂石', '韩诀', 'cross_hit', 'flex_qi', 'high_hp'],
  ['longnv', '龙女', 'baxian', 'rare', 'st_heal', '献珠疗伤', '龙诀', 'heal_low', 'first_strike', 'amp_def'],
  ['lancahe', '蓝采和', 'baxian', 'common', 'aoe_ctrl', '花篮困步', '蓝诀', 'mass_slow', 'slow_pin', 'flex_qi'],
  ['caoguojiu', '曹国舅', 'baxian', 'common', 'tank', '朝笏护众', '曹诀', 'team_wall', 'flex_bleed', 'first_strike'],
  ['baimudan', '白牡丹', 'baxian', 'common', 'st_ctrl', '花下禁息', '白牡丹·白诀', 'heal_block', 'amp_def', 'flex_bleed'],
  ['xishi', '西施', 'wuyue', 'legendary', 'st_ctrl', '浣纱沉鱼', '沉鱼一笑', 'heal_block', 'amp_def', 'flex_bleed'],
  ['nieyinniang', '聂隐娘', 'wuyue', 'legendary', 'st_burst', '飞剑取首', '隐娘刺', 'execute', 'amp_def', 'flex_bleed'],
  ['jingke', '荆轲', 'wuyue', 'legendary', 'st_burst', '图穷匕见', '图穷匕见', 'hunt_back', 'slow_pin', 'flex_qi'],
  ['ganjiang', '干将', 'wuyue', 'legendary', 'aoe_dps', '铸剑开锋', '干诀', 'col_wave', 'heal_low', 'amp_def'],
  ['moye', '莫邪', 'wuyue', 'legendary', 'st_burst', '雌剑噬满', '莫诀', 'high_hp', 'surround_aoe', 'heal_low'],
  ['libai', '李白', 'wuyue', 'legendary', 'aoe_dps', '斗酒诗百', '将进酒', 'surround_aoe', 'first_strike', 'slow_pin'],
  ['wuzixu', '伍子胥', 'wuyue', 'legendary', 'tank', '过昭关夜', '伍诀', 'hp_guard', 'flex_qi', 'high_hp'],
  ['hongxian', '红线', 'wuyue', 'epic', 'flex', '夜盗金盒', '红线·红诀', 'flex_qi', 'flex_bleed', 'first_strike'],
  ['fanli', '范蠡', 'wuyue', 'epic', 'group_amp', '扁舟五湖', '范诀', 'amp_spd', 'heal_low', 'amp_def'],
  ['gaojianli', '高渐离', 'wuyue', 'epic', 'aoe_ctrl', '筑声困神', '高诀', 'mass_sleep', 'first_strike', 'slow_pin'],
  ['zhuanzhu', '专诸', 'wuyue', 'rare', 'st_burst', '鱼肠先发', '专诀', 'first_strike', 'flex_bleed', 'mark_hunt'],
  ['kunlunnu', '昆仑奴', 'wuyue', 'rare', 'tank', '负主突围', '昆诀', 'guard', 'heal_low', 'amp_def'],
  ['yuenv', '越女', 'wuyue', 'rare', 'st_burst', '越女剑贯', '越诀', 'col_kill', 'flex_qi', 'high_hp'],
  ['yaoli', '要离', 'wuyue', 'common', 'st_ctrl', '残身刺庆', '要诀', 'sleep', 'slow_pin', 'flex_qi'],
  ['yuangong', '袁公', 'wuyue', 'common', 'flex', '白猿授剑', '袁诀', 'first_strike', 'flex_qi', 'high_hp'],
  ['baisuzhen', '白素贞', 'jiangnan', 'legendary', 'aoe_heal', '西湖救许', '白素贞·白诀', 'heal_cleanse', 'amp_def', 'flex_bleed'],
  ['xiaoqing', '小青', 'jiangnan', 'legendary', 'st_burst', '青蛇猎印', '小青·小诀', 'mark_hunt', 'heal_low', 'amp_def'],
  ['fahai', '法海', 'jiangnan', 'legendary', 'st_ctrl', '钵印迟妖', '法诀', 'slow_pin', 'surround_aoe', 'heal_low'],
  ['zhinu', '织女', 'jiangnan', 'legendary', 'aoe_heal', '鹊桥织锦', '织诀', 'team_heal', 'slow_pin', 'flex_qi'],
  ['qixiannv', '七仙女', 'jiangnan', 'epic', 'aoe_heal', '天衣覆护', '七诀', 'team_aegis', 'surround_aoe', 'heal_low'],
  ['liangshanbo', '梁山伯', 'jiangnan', 'epic', 'flex', '草桥结拜', '梁诀', 'flex_purge', 'heal_low', 'amp_def'],
  ['zhuyingtai', '祝英台', 'jiangnan', 'epic', 'st_burst', '女扮赴杭', '祝英台·祝诀', 'bleed_pierce', 'first_strike', 'slow_pin'],
  ['niulang', '牛郎', 'jiangnan', 'rare', 'flex', '金牛踏天', '牛诀', 'flex_first', 'first_strike', 'slow_pin'],
  ['mengjiangnv', '孟姜女', 'jiangnan', 'rare', 'aoe_ctrl', '哭倒长城', '孟姜女·孟诀', 'slow_pin', 'high_hp', 'surround_aoe'],
  ['xuxian', '许仙', 'jiangnan', 'common', 'st_heal', '药铺续命', '许仙·许诀', 'regen', 'first_strike', 'slow_pin'],
  ['wanxiliang', '万喜良', 'jiangnan', 'common', 'tank', '城砖埋骨', '万诀', 'earth', 'high_hp', 'surround_aoe'],
  ['dongyong', '董永', 'jiangnan', 'common', 'group_amp', '槐荫约织', '董诀', 'qi_drought', 'first_strike', 'slow_pin'],
  ['xiangyu', '项羽', 'chuhan', 'legendary', 'aoe_dps', '不肯过江', '破釜沉舟', 'first_wave', 'high_hp', 'surround_aoe'],
  ['liubang', '刘邦', 'chuhan', 'legendary', 'group_amp', '约法三章', '刘诀', 'amp_def', 'high_hp', 'surround_aoe'],
  ['hanxin', '韩信', 'chuhan', 'legendary', 'group_amp', '背水一战', '韩信·韩诀', 'amp_atk', 'amp_def', 'flex_bleed'],
  ['zhangliang', '张良', 'chuhan', 'legendary', 'st_ctrl', '进履得书', '张良·张诀', 'stun', 'flex_bleed', 'first_strike'],
  ['yuji', '虞姬', 'chuhan', 'legendary', 'aoe_heal', '垓下舞剑', '虞诀', 'heal_low', 'flex_bleed', 'first_strike'],
  ['fanzeng', '范增', 'chuhan', 'epic', 'aoe_ctrl', '鸿门玉玦', '范增·范诀', 'havoc', 'amp_def', 'flex_bleed'],
  ['xiaohe', '萧何', 'chuhan', 'epic', 'group_amp', '月下追韩', '萧诀', 'amp_qi', 'slow_pin', 'flex_qi'],
  ['yingbu', '英布', 'chuhan', 'rare', 'st_burst', '九江斩将', '英诀', 'execute', 'high_hp', 'surround_aoe'],
  ['fankuai', '樊哙', 'chuhan', 'rare', 'tank', '闯帐对卮', '樊诀', 'earth', 'high_hp', 'surround_aoe'],
  ['quyuan', '屈原', 'chuhan', 'epic', 'st_heal', '怀沙问天', '屈诀', 'heal_cleanse', 'high_hp', 'surround_aoe'],
  ['xiangbo', '项伯', 'chuhan', 'common', 'flex', '项伯夜驰', '项诀', 'flex_stun', 'amp_def', 'flex_bleed'],
  ['pengyue', '彭越', 'chuhan', 'common', 'aoe_dps', '梁地起兵', '彭诀', 'row_smash', 'amp_def', 'flex_bleed'],
  ['guiguzi', '鬼谷子', 'bingjia', 'legendary', 'group_amp', '纵横捭阖', '鬼诀', 'amp_spd', 'surround_aoe', 'heal_low'],
  ['sunbin', '孙膑', 'bingjia', 'legendary', 'group_amp', '减灶诱敌', '减灶', 'shred_trap', 'qi_drought', 'amp_qi'],
  ['sunwu', '孙武', 'bingjia', 'legendary', 'group_amp', '不战屈人', '孙武·孙诀', 'qi_drought', 'flex_bleed', 'first_strike'],
  ['gongshuban', '公输班', 'bingjia', 'legendary', 'tank', '云梯攻城', '公诀', 'shred_guard', 'taunt', 'earth'],
  ['pangjuan', '庞涓', 'bingjia', 'legendary', 'st_burst', '马陵争道', '庞诀', 'hunt_back', 'amp_def', 'flex_bleed'],
  ['wuqi', '吴起', 'bingjia', 'epic', 'flex', '杀妻求将', '吴诀', 'flex_stun', 'amp_def', 'flex_bleed'],
  ['suqin', '苏秦', 'bingjia', 'rare', 'st_ctrl', '合纵封喉', '苏诀', 'silence', 'flex_qi', 'high_hp'],
  ['zhangyi', '张仪', 'bingjia', 'rare', 'aoe_ctrl', '连横迟众', '张仪·张诀', 'mass_slow', 'slow_pin', 'flex_qi'],
  ['yueyi', '乐毅', 'bingjia', 'rare', 'aoe_dps', '乐毅伐齐', '乐诀', 'cross_hit', 'slow_pin', 'flex_qi'],
  ['mozi', '墨子', 'bingjia', 'epic', 'tank', '非攻守城', '墨诀', 'first_guard', 'amp_def', 'flex_bleed'],
  ['yuefei', '岳飞', 'zhonglie', 'legendary', 'st_burst', '还我河山', '精忠枪', 'high_hp', 'slow_pin', 'flex_qi'],
  ['muguiying', '穆桂英', 'zhonglie', 'legendary', 'aoe_dps', '挂帅破阵', '穆诀', 'col_wave', 'surround_aoe', 'heal_low'],
  ['yangye', '杨业', 'zhonglie', 'legendary', 'tank', '李陵碑前', '杨诀', 'team_wall', 'slow_pin', 'flex_qi'],
  ['mulan', '花木兰', 'zhonglie', 'legendary', 'flex', '替父从军', '花诀', 'flex_qi', 'slow_pin', 'flex_purge'],
  ['shetaijun', '佘太君', 'zhonglie', 'legendary', 'group_amp', '佘太君点将', '佘诀', 'amp_def', 'flex_qi', 'high_hp'],
  ['lianghongyu', '梁红玉', 'zhonglie', 'epic', 'aoe_ctrl', '金山擂鼓', '梁红玉·梁诀', 'mass_silence', 'surround_aoe', 'heal_low'],
  ['yangyanzhao', '杨延昭', 'zhonglie', 'epic', 'st_burst', '六郎镇关', '杨延昭·杨诀', 'first_strike', 'surround_aoe', 'heal_low'],
  ['yangpaifeng', '杨排风', 'zhonglie', 'rare', 'st_burst', '烧火杨排风', '杨排风·杨诀', 'col_kill', 'flex_bleed', 'first_strike'],
  ['yueyun', '岳云', 'zhonglie', 'rare', 'st_burst', '锤走朱仙', '岳诀', 'mark_hunt', 'flex_qi', 'high_hp'],
  ['hanshizhong', '韩世忠', 'zhonglie', 'epic', 'tank', '黄天荡锁', '韩世忠·韩诀', 'hp_guard', 'surround_aoe', 'heal_low'],
  ['yangzongbao', '杨宗保', 'zhonglie', 'common', 'flex', '穆柯寨约', '杨宗保·杨诀', 'flex_purge', 'flex_bleed', 'first_strike'],
  ['zhangxian', '张宪', 'zhonglie', 'common', 'tank', '岳家亲军', '张宪·张诀', 'first_guard', 'first_strike', 'slow_pin'],
  ['linchong', '林冲', 'liangshan', 'legendary', 'st_burst', '风雪山神', '豹子头', 'bleed_pierce', 'heal_low', 'amp_def'],
  ['wusong', '武松', 'liangshan', 'legendary', 'st_burst', '打虎景阳', '景阳冈', 'execute', 'first_strike', 'slow_pin'],
  ['luzhishen', '鲁智深', 'liangshan', 'legendary', 'tank', '倒拔垂杨', '倒拔垂杨', 'taunt', 'flex_qi', 'high_hp'],
  ['songjiang', '宋江', 'liangshan', 'legendary', 'group_amp', '及时雨令', '宋诀', 'amp_atk', 'heal_low', 'amp_def'],
  ['wuyong', '吴用', 'liangshan', 'epic', 'group_amp', '智多星策', '吴用·吴诀', 'amp_qi', 'first_strike', 'slow_pin'],
  ['lujunyi', '卢俊义', 'liangshan', 'epic', 'flex', '玉麒麟醒', '卢诀', 'flex_purge', 'flex_bleed', 'first_strike'],
  ['likui', '李逵', 'liangshan', 'epic', 'aoe_dps', '板斧开路', '李逵·李诀', 'surround_aoe', 'flex_bleed', 'first_strike'],
  ['gongsunsheng', '公孙胜', 'liangshan', 'rare', 'aoe_ctrl', '入云龙困', '公孙胜·公诀', 'mass_sleep', 'flex_bleed', 'first_strike'],
  ['husanniang', '扈三娘', 'liangshan', 'rare', 'st_burst', '一丈青骑', '扈诀', 'hunt_back', 'high_hp', 'surround_aoe'],
  ['huarong', '花荣', 'liangshan', 'rare', 'st_burst', '小李广射', '花荣·花诀', 'high_hp', 'amp_def', 'flex_bleed'],
  ['yanqing', '燕青', 'liangshan', 'rare', 'flex', '浪子燕青', '燕诀', 'flex_first', 'flex_qi', 'high_hp'],
  ['chaijin', '柴进', 'liangshan', 'common', 'aoe_heal', '小旋风济', '柴诀', 'heal_cleanse', 'flex_qi', 'high_hp'],
  ['qinqiong', '秦琼', 'wagang', 'legendary', 'tank', '锏震瓦岗', '秦诀', 'earth', 'heal_low', 'amp_def'],
  ['lishimin', '李世民', 'wagang', 'legendary', 'group_amp', '天策开府', '天策府', 'amp_spd', 'high_hp', 'surround_aoe'],
  ['yuchigong', '尉迟恭', 'wagang', 'legendary', 'tank', '黑鞭守门', '尉诀', 'first_guard', 'first_strike', 'slow_pin'],
  ['luocheng', '罗成', 'wagang', 'legendary', 'st_burst', '银枪先发', '罗诀', 'first_strike', 'slow_pin', 'flex_qi'],
  ['shanxiongxin', '单雄信', 'wagang', 'epic', 'st_burst', '金刀贯列', '单诀', 'col_kill', 'surround_aoe', 'heal_low'],
  ['xumaogong', '徐茂公', 'wagang', 'epic', 'group_amp', '神机闭气', '徐茂公·徐诀', 'qi_drought', 'amp_def', 'flex_bleed'],
  ['chengyaojin', '程咬金', 'wagang', 'epic', 'aoe_dps', '三斧定瓦', '程诀', 'first_wave', 'flex_qi', 'high_hp'],
  ['weizheng', '魏征', 'wagang', 'rare', 'st_ctrl', '直谏禁疗', '魏征·魏诀', 'heal_block', 'heal_low', 'amp_def'],
  ['wangbodang', '王伯当', 'wagang', 'rare', 'flex', '箭雨带刃', '王诀', 'flex_bleed', 'heal_low', 'amp_def'],
  ['peiyuanqing', '裴元庆', 'wagang', 'rare', 'st_burst', '锤标猎印', '裴诀', 'mark_hunt', 'flex_bleed', 'first_strike'],
  ['limi', '李密', 'wagang', 'common', 'flex', '魏公余令', '李密·李诀', 'flex_qi', 'high_hp', 'surround_aoe'],
  ['wuyunzhao', '伍云召', 'wagang', 'common', 'aoe_dps', '鞭扫十字', '伍云召·伍诀', 'cross_hit', 'first_strike', 'slow_pin'],
  ['chenxiang', '沉香', 'baolian', 'legendary', 'st_burst', '斧劈华山', '斧劈华山', 'bleed_pierce', 'flex_qi', 'high_hp'],
  ['sanshengmu', '三圣母', 'baolian', 'legendary', 'aoe_heal', '宝莲灯暖', '三诀', 'team_heal', 'heal_low', 'amp_def'],
  ['pili', '霹雳大仙', 'baolian', 'rare', 'aoe_dps', '霹雳十字', '霹诀', 'cross_hit', 'first_strike', 'slow_pin'],
  ['gashan', '嘎善', 'baolian', 'rare', 'tank', '嘎善金甲', '嘎诀', 'team_wall', 'high_hp', 'surround_aoe'],
  ['liuyanchang', '刘彦昌', 'baolian', 'common', 'st_heal', '书生济伤', '刘彦昌·刘诀', 'heal_low', 'amp_def', 'flex_bleed'],
  ['zhongkui', '钟馗', 'xiangyao', 'legendary', 'tank', '捉鬼啖邪', '捉鬼啖邪', 'hp_guard', 'amp_def', 'flex_bleed'],
  ['xuxun', '许逊', 'xiangyao', 'legendary', 'aoe_dps', '斩蛟贯列', '许逊·许诀', 'col_wave', 'high_hp', 'surround_aoe'],
  ['jigong', '济公', 'xiangyao', 'legendary', 'aoe_heal', '癫僧覆袖', '济诀', 'team_aegis', 'first_strike', 'slow_pin'],
  ['zhangdaoling', '张道陵', 'xiangyao', 'legendary', 'st_ctrl', '龙虎山睡', '张道陵·张诀', 'sleep', 'first_strike', 'slow_pin'],
  ['sazhenren', '萨真人', 'xiangyao', 'rare', 'group_amp', '萨公铁壁', '萨诀', 'amp_def', 'slow_pin', 'flex_qi'],
  ['wanglingguan', '王灵官', 'xiangyao', 'rare', 'st_burst', '金鞭斩邪', '王灵官·王诀', 'execute', 'heal_low', 'amp_def'],
  ['cuipanguan', '崔判官', 'xiangyao', 'rare', 'st_ctrl', '判笔迟魂', '崔诀', 'slow_pin', 'high_hp', 'surround_aoe'],
  ['wuchang', '黑白无常', 'xiangyao', 'common', 'aoe_ctrl', '勾魂迟步', '黑诀', 'slow_pin', 'surround_aoe', 'flex_qi'],
  ['niexiaoqian', '聂小倩', 'liaozhai', 'legendary', 'st_ctrl', '兰若惊魂', '聂诀', 'stun', 'amp_def', 'flex_bleed'],
  ['yanchixia', '燕赤霞', 'liaozhai', 'legendary', 'st_burst', '道袍猎妖', '燕赤霞·燕诀', 'hunt_back', 'first_strike', 'slow_pin'],
  ['huapi', '画皮', 'liaozhai', 'legendary', 'aoe_ctrl', '画皮换面', '画皮换面', 'havoc', 'heal_low', 'amp_def'],
  ['lupan', '陆判', 'liaozhai', 'epic', 'group_amp', '换心增威', '陆判·陆诀', 'amp_atk', 'surround_aoe', 'heal_low'],
  ['yingning', '婴宁', 'liaozhai', 'epic', 'aoe_heal', '笑愈心伤', '婴诀', 'heal_low', 'high_hp', 'surround_aoe'],
  ['lianxiang', '莲香', 'liaozhai', 'rare', 'st_heal', '莲香续命', '莲诀', 'regen', 'slow_pin', 'flex_qi'],
  ['jiaona', '娇娜', 'liaozhai', 'rare', 'flex', '娇娜补气', '娇诀', 'flex_qi', 'high_hp', 'surround_aoe'],
  ['ningcaisen', '宁采臣', 'liaozhai', 'common', 'flex', '书生先手', '宁诀', 'first_strike', 'high_hp', 'slow_pin'],
  ['hero', '主角', null, 'legendary', 'flex', '无名行者补位', '破妄斩', 'flex_purge', 'slow_pin', 'flex_qi'],
];

export const ZHONGTU_ROSTER: ZhongtuEntry[] = ROWS.map((r) => {
  const [id, name, circleId, rarity, role, motif, skillName, k1, k2, k3] = r;
  return {
    id,
    name,
    circleId,
    rarity,
    role,
    motif,
    skillName,
    lore: circleId ? CIRCLE_LABELS[circleId] : '旅途',
    unlock: unlockFor(id, circleId, rarity),
    kits: [k1, k2, k3],
  };
});

const byId = new Map(ZHONGTU_ROSTER.map((e) => [e.id, e]));

export function getZhongtuEntry(id: string): ZhongtuEntry | undefined {
  return byId.get(id);
}

